// Package generator executes code-generation templates against a parsed model
// to produce typed client libraries. It embeds all templates from the templates/
// directory and writes generated Go source files to the specified output directory.
package generator

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
	"unicode"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/model"
)

//go:embed templates/*.tmpl
var templateFS embed.FS

// header is prepended to every generated file.
const header = "// Code generated by modusGraphGen. DO NOT EDIT.\n\n"

// generateConfig holds optional configuration for Generate.
type generateConfig struct {
	CLIDir string // Absolute path for CLI output; empty means default ({outputDir}/cmd/{name}).
}

// GenerateOption configures code generation.
type GenerateOption func(*generateConfig)

// WithCLIDir sets the output directory for the generated CLI main.go.
// When empty (the default), the CLI is generated at {outputDir}/cmd/{packageName}/main.go.
func WithCLIDir(dir string) GenerateOption {
	return func(c *generateConfig) { c.CLIDir = dir }
}

// Generate renders all code-generation templates against pkg and writes the
// resulting Go source files into outputDir. The directory must already exist.
func Generate(pkg *model.Package, outputDir string, opts ...GenerateOption) error {
	cfg := &generateConfig{}
	for _, opt := range opts {
		opt(cfg)
	}

	// Default CLIName to the package name if not explicitly set.
	if pkg.CLIName == "" {
		pkg.CLIName = pkg.Name
	}
	// Sort entities by name for deterministic output.
	sort.Slice(pkg.Entities, func(i, j int) bool {
		return pkg.Entities[i].Name < pkg.Entities[j].Name
	})
	funcMap := template.FuncMap{
		"toLower":      strings.ToLower,
		"toUpper":      strings.ToUpper,
		"toSnakeCase":  toSnakeCase,
		"toCamelCase":  toCamelCase,
		"accessorName": accessorName,
		"toLowerCamel": toLowerCamel,
		"title":        strings.Title, //nolint:staticcheck
		"hasPrefix":    strings.HasPrefix,
		"hasSuffix":    strings.HasSuffix,
		"contains":     strings.Contains,
		"trimPrefix":   strings.TrimPrefix,
		"join":         strings.Join,
		"sub":          func(a, b int) int { return a - b },
		"add":          func(a, b int) int { return a + b },

		// Field helpers for templates.
		"scalarFields":              scalarFields,
		"edgeFields":                edgeFields,
		"searchPredicate":           searchPredicate,
		"externalImports":           externalImports,
		"nonSliceScalarFields":      nonSliceScalarFields,
		"hasPrivateFields":          hasPrivateFields,
		"privateFields":             privateFields,
		"privateScalarFields":       privateScalarFields,
		"privateSingularEdgeFields": privateSingularEdgeFields,
		"privateMultiEdgeFields":    privateMultiEdgeFields,
		"privateSliceFields":        privateSliceFields,
		"allSingularEdgeFields":     allSingularEdgeFields,
		"allMultiEdgeFields":        allMultiEdgeFields,
		"allSliceFields":            allSliceFields,
		"marshalFields":             marshalFields,
		"packageExternalImports":    packageExternalImports,
		"elemType":                  elemType,
		"cliType":                   cliType,
		"cliConvert":                cliConvert,
		"hasValidateTags":           hasValidateTags,
		"fieldsWithValidation":      fieldsWithValidation,
		"lcFirst":                   lcFirst,
	}

	tmpl, err := template.New("").Funcs(funcMap).ParseFS(templateFS, "templates/*.tmpl")
	if err != nil {
		return fmt.Errorf("parsing templates: %w", err)
	}

	// 1. client.go.tmpl → client_gen.go (once)
	if err := executeAndWrite(tmpl, "client.go.tmpl", pkg, filepath.Join(outputDir, "client_gen.go")); err != nil {
		return err
	}

	// 2. page_options.go.tmpl → page_options_gen.go (once)
	if err := executeAndWrite(tmpl, "page_options.go.tmpl", pkg, filepath.Join(outputDir, "page_options_gen.go")); err != nil {
		return err
	}

	// 3. iter.go.tmpl → iter_gen.go (once)
	if err := executeAndWrite(tmpl, "iter.go.tmpl", pkg, filepath.Join(outputDir, "iter_gen.go")); err != nil {
		return err
	}

	// Per-entity templates.
	type entityData struct {
		PackageName string
		Entity      model.Entity
		Entities    []model.Entity
		Imports     map[string]string // Package alias → import path
	}

	for _, entity := range pkg.Entities {
		data := entityData{
			PackageName: pkg.Name,
			Entity:      entity,
			Entities:    pkg.Entities,
			Imports:     pkg.Imports,
		}
		snake := toSnakeCase(entity.Name)

		// 4. entity.go.tmpl → <snake>_gen.go
		if err := executeAndWrite(tmpl, "entity.go.tmpl", data, filepath.Join(outputDir, snake+"_gen.go")); err != nil {
			return err
		}

		// 5. options.go.tmpl → <snake>_options_gen.go
		if err := executeAndWrite(tmpl, "options.go.tmpl", data, filepath.Join(outputDir, snake+"_options_gen.go")); err != nil {
			return err
		}

		// 6. query.go.tmpl → <snake>_query_gen.go
		if err := executeAndWrite(tmpl, "query.go.tmpl", data, filepath.Join(outputDir, snake+"_query_gen.go")); err != nil {
			return err
		}

		// 7. accessors.go.tmpl → <snake>_accessors_gen.go (only if entity has private fields)
		if hasPrivateFields(entity.Fields) {
			if err := executeAndWrite(tmpl, "accessors.go.tmpl", data, filepath.Join(outputDir, snake+"_accessors_gen.go")); err != nil {
				return err
			}
		}

		// 8. marshal.go.tmpl → <snake>_marshal_gen.go (only if entity has private fields)
		if hasPrivateFields(entity.Fields) {
			if err := executeAndWrite(tmpl, "marshal.go.tmpl", data, filepath.Join(outputDir, snake+"_marshal_gen.go")); err != nil {
				return err
			}
		}
	}

	// 7. cli.go.tmpl → cmd/<name>/main.go (stub)
	cliDir := cfg.CLIDir
	if cliDir == "" {
		cliDir = filepath.Join(outputDir, "cmd", pkg.Name)
	}
	if err := os.MkdirAll(cliDir, 0o755); err != nil {
		return fmt.Errorf("creating CLI directory: %w", err)
	}
	if err := executeAndWrite(tmpl, "cli.go.tmpl", pkg, filepath.Join(cliDir, "main.go")); err != nil {
		return err
	}

	return nil
}

// executeAndWrite renders a named template and writes the gofmt'd result to path.
func executeAndWrite(tmpl *template.Template, name string, data any, path string) error {
	var buf bytes.Buffer
	buf.WriteString(header)

	if err := tmpl.ExecuteTemplate(&buf, name, data); err != nil {
		return fmt.Errorf("executing template %s: %w", name, err)
	}

	// Format the output with gofmt.
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		// Write the unformatted output for debugging.
		_ = os.WriteFile(path+".broken", buf.Bytes(), 0o644)
		return fmt.Errorf("formatting %s: %w\nRaw output written to %s.broken", name, err, path)
	}

	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", path, err)
	}

	return nil
}

// toSnakeCase converts a Go identifier like "ContentRating" to "content_rating".
func toSnakeCase(s string) string {
	var result strings.Builder
	for i, r := range s {
		if unicode.IsUpper(r) {
			if i > 0 {
				prev := rune(s[i-1])
				if unicode.IsLower(prev) || (i+1 < len(s) && unicode.IsLower(rune(s[i+1]))) {
					result.WriteRune('_')
				}
			}
			result.WriteRune(unicode.ToLower(r))
		} else {
			result.WriteRune(r)
		}
	}
	return result.String()
}

// commonInitialisms is the canonical set of Go initialisms from golang.org/x/lint.
// These are uppercased as a whole word in CamelCase identifiers per Go conventions.
// Source: https://github.com/golang/lint/blob/master/lint.go (BSD-3-Clause)
var commonInitialisms = map[string]bool{
	"ACL":   true,
	"API":   true,
	"ASCII": true,
	"CPU":   true,
	"CSS":   true,
	"DNS":   true,
	"EOF":   true,
	"GUID":  true,
	"HTML":  true,
	"HTTP":  true,
	"HTTPS": true,
	"ID":    true,
	"IP":    true,
	"JSON":  true,
	"LHS":   true,
	"QPS":   true,
	"RAM":   true,
	"RHS":   true,
	"RPC":   true,
	"SLA":   true,
	"SMTP":  true,
	"SQL":   true,
	"SSH":   true,
	"TCP":   true,
	"TLS":   true,
	"TTL":   true,
	"UDP":   true,
	"UI":    true,
	"UID":   true,
	"UUID":  true,
	"URI":   true,
	"URL":   true,
	"UTF8":  true,
	"VM":    true,
	"XML":   true,
	"XMPP":  true,
	"XSRF":  true,
	"XSS":   true,
}

// toCamelCase converts a snake_case or lowercase string to CamelCase with
// Go initialism awareness. Known initialisms (ID, URL, HTTP, etc.) are
// uppercased as a whole word per Go naming conventions.
func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		upper := strings.ToUpper(p)
		if commonInitialisms[upper] {
			result.WriteString(upper)
		} else {
			result.WriteString(strings.ToUpper(p[:1]))
			result.WriteString(p[1:])
		}
	}
	return result.String()
}

// accessorName returns the exported name to use for generated accessor methods
// on the given field. If the field has an explicit AccessorName override (from
// the `accessor` struct tag), it is returned as-is. Otherwise, the field name
// is run through toCamelCase with initialism awareness.
func accessorName(f model.Field) string {
	if f.AccessorName != "" {
		return f.AccessorName
	}
	return toCamelCase(f.Name)
}

// toLowerCamel converts an identifier to lowerCamelCase.
func toLowerCamel(s string) string {
	if len(s) == 0 {
		return s
	}
	// If already CamelCase, just lower the first letter.
	return strings.ToLower(s[:1]) + s[1:]
}

// scalarFields returns fields that are not UID, DType, or edges.
func scalarFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsUID || f.IsDType || f.IsEdge {
			continue
		}
		result = append(result, f)
	}
	return result
}

// nonSliceScalarFields returns scalar fields that are not slices.
// Used in marshal templates to avoid double-emitting slice fields.
func nonSliceScalarFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsUID || f.IsDType || f.IsEdge || strings.HasPrefix(f.GoType, "[]") {
			continue
		}
		result = append(result, f)
	}
	return result
}

// edgeFields returns only edge fields.
func edgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsEdge {
			result = append(result, f)
		}
	}
	return result
}

// privateFields returns all private, non-skipped, non-UID, non-DType fields.
func privateFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPrivate && !f.IsSkipped && !f.IsUID && !f.IsDType {
			result = append(result, f)
		}
	}
	return result
}

// hasPrivateFields returns true if any field is private and not skipped.
func hasPrivateFields(fields []model.Field) bool {
	for _, f := range fields {
		if f.IsPrivate && !f.IsSkipped && !f.IsUID && !f.IsDType {
			return true
		}
	}
	return false
}

// privateScalarFields returns private non-edge, non-UID, non-DType fields
// that are not slices (simple scalars like string, int, time.Time).
func privateScalarFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPrivate && !f.IsUID && !f.IsDType && !f.IsEdge && !strings.HasPrefix(f.GoType, "[]") {
			result = append(result, f)
		}
	}
	return result
}

// privateSingularEdgeFields returns private edge fields where IsSingularEdge is true.
func privateSingularEdgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPrivate && f.IsEdge && f.IsSingularEdge {
			result = append(result, f)
		}
	}
	return result
}

// privateMultiEdgeFields returns private edge fields where IsSingularEdge is false.
func privateMultiEdgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPrivate && f.IsEdge && !f.IsSingularEdge {
			result = append(result, f)
		}
	}
	return result
}

// privateSliceFields returns private non-edge slice fields (e.g., []string, []float64).
func privateSliceFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsPrivate && !f.IsEdge && strings.HasPrefix(f.GoType, "[]") && !f.IsUID && !f.IsDType {
			result = append(result, f)
		}
	}
	return result
}

// allSingularEdgeFields returns all edge fields (public and private) where IsSingularEdge is true.
func allSingularEdgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsEdge && f.IsSingularEdge {
			result = append(result, f)
		}
	}
	return result
}

// allMultiEdgeFields returns all edge fields (public and private) where IsSingularEdge is false.
func allMultiEdgeFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsEdge && !f.IsSingularEdge {
			result = append(result, f)
		}
	}
	return result
}

// allSliceFields returns all non-edge slice fields (public and private).
func allSliceFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if !f.IsEdge && strings.HasPrefix(f.GoType, "[]") && !f.IsUID && !f.IsDType {
			result = append(result, f)
		}
	}
	return result
}

// marshalFields returns all non-UID, non-DType, non-skipped fields (both public and private).
// This is the union of fields that appear in the marshal alias and mirror structs,
// used to compute which external package imports the marshal file needs.
func marshalFields(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.IsSkipped || f.IsUID || f.IsDType {
			continue
		}
		result = append(result, f)
	}
	return result
}

// packageExternalImports returns the union of external imports needed across all
// entities in the package. This is used by the CLI template which lives in a
// separate main package and needs to import external types for conversions.
func packageExternalImports(pkg *model.Package) []ImportSpec {
	var allFields []model.Field
	for _, entity := range pkg.Entities {
		allFields = append(allFields, marshalFields(entity.Fields)...)
	}
	return externalImports(allFields, pkg.Imports)
}

// lcFirst lowercases the first character of a string.
func lcFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

// elemType strips the leading "[]" from a Go type string, returning the element type.
func elemType(goType string) string {
	return strings.TrimPrefix(goType, "[]")
}

// cliType maps a Go type to the appropriate type for a Kong CLI struct field.
// Kong natively parses string, int, float64, bool, and time.Time flags.
func cliType(goType string) string {
	switch goType {
	case "string", "int", "int64", "float64", "bool":
		return goType
	case "int32":
		return "int"
	case "float32":
		return "float64"
	case "time.Time":
		return "string" // Parsed as string, converted in Run()
	default:
		return "string" // Fallback: accept as string
	}
}

// cliConvert returns a Go expression that converts a CLI field value to the
// entity field's Go type. For types that Kong handles natively (string, int,
// float64, bool), this is an identity — the value is already the correct type.
// For time.Time, this wraps with time.Parse. For external types (e.g.,
// enums.ArchiveStatus, scalars.UUID) that are represented as strings in the
// CLI, this wraps with a type conversion.
func cliConvert(goType, expr string) string {
	switch goType {
	case "string", "int", "int64", "float64", "bool":
		return expr
	case "int32":
		return "int32(" + expr + ")"
	case "float32":
		return "float32(" + expr + ")"
	default:
		// External types (enums, scalars, etc.) are accepted as strings by
		// the CLI and need an explicit type conversion to the target type.
		return goType + "(" + expr + ")"
	}
}

// hasValidateTags returns true if any field has a non-empty ValidateTag.
func hasValidateTags(fields []model.Field) bool {
	for _, f := range fields {
		if f.ValidateTag != "" {
			return true
		}
	}
	return false
}

// fieldsWithValidation returns fields that have a non-empty ValidateTag.
func fieldsWithValidation(fields []model.Field) []model.Field {
	var result []model.Field
	for _, f := range fields {
		if f.ValidateTag != "" {
			result = append(result, f)
		}
	}
	return result
}

// ImportSpec represents a Go import with an optional alias.
type ImportSpec struct {
	Alias string // Non-empty only when the alias differs from the last path segment.
	Path  string // Full import path.
}

// externalImports returns a sorted list of import specs needed by the given
// fields. It scans field GoTypes for package-qualified types (containing a dot
// that isn't "time."), looks up the full import path in the imports map, and
// returns the unique set. Standard library packages like "time" are excluded
// because templates handle them separately. If a package was imported with an
// alias that differs from the last path segment, the ImportSpec includes the
// alias so templates can emit `alias "path"` syntax.
func externalImports(fields []model.Field, imports map[string]string) []ImportSpec {
	seen := make(map[string]bool)
	var result []ImportSpec
	for _, f := range fields {
		// Strip pointer/slice prefixes to find the package qualifier.
		goType := strings.TrimLeft(f.GoType, "[]*")
		dot := strings.IndexByte(goType, '.')
		if dot < 0 {
			continue
		}
		// Extract the package alias (e.g., "enums" from "enums.ResourceType").
		pkgAlias := goType[:dot]
		// Skip standard library packages that are handled directly in templates.
		if pkgAlias == "time" {
			continue
		}
		path, ok := imports[pkgAlias]
		if !ok || seen[path] {
			continue
		}
		seen[path] = true
		// Include alias only when it differs from the last path segment.
		parts := strings.Split(path, "/")
		alias := ""
		if pkgAlias != parts[len(parts)-1] {
			alias = pkgAlias
		}
		result = append(result, ImportSpec{Alias: alias, Path: path})
	}
	sort.Slice(result, func(i, j int) bool { return result[i].Path < result[j].Path })
	return result
}

// searchPredicate returns the dgraph predicate name for the entity's search
// field, or empty string if not searchable.
func searchPredicate(entity model.Entity) string {
	if !entity.Searchable {
		return ""
	}
	for _, f := range entity.Fields {
		if f.Name == entity.SearchField {
			return f.Predicate
		}
	}
	return ""
}
