// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// ActorQuery is a fluent query builder for Actor records. Terminal
// methods (Nodes, First) execute the query against the underlying
// modusgraph.Client and populate raw *Actor results.
type ActorQuery struct {
	ctx  context.Context
	conn modusgraph.Client
}

// NewActorQuery constructs a query bound to ctx and conn. Callers
// usually obtain one via ActorClient.Query rather than directly.
func NewActorQuery(ctx context.Context, conn modusgraph.Client) *ActorQuery {
	return &ActorQuery{ctx: ctx, conn: conn}
}

// Nodes executes the query and decodes results into recs. recs must be a
// pointer to a []Actor or []*Actor slice.
func (q *ActorQuery) Nodes(recs any) error {
	return q.conn.Query(q.ctx, &Actor{}).Nodes(recs)
}

// First runs the query with implicit Limit=1 and returns the first
// Actor record, or nil if the query yielded no rows.
func (q *ActorQuery) First() (*Actor, error) {
	var recs []Actor
	if err := q.Nodes(&recs); err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, nil
	}
	return &recs[0], nil
}
