// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// ActorClient provides CRUD/query operations over Actor records.
// Takes and returns *Actor directly — no wrapper allocation.
type ActorClient struct {
	conn modusgraph.Client
}

// NewActorClient binds a ActorClient to conn.
func NewActorClient(conn modusgraph.Client) *ActorClient {
	return &ActorClient{conn: conn}
}

// Get loads the Actor with the given UID.
func (c *ActorClient) Get(ctx context.Context, uid string) (*Actor, error) {
	var rec Actor
	if err := c.conn.Get(ctx, &rec, uid); err != nil {
		return nil, err
	}
	return &rec, nil
}

// Add inserts a new Actor.
func (c *ActorClient) Add(ctx context.Context, s *Actor) error {
	return c.conn.Insert(ctx, s)
}

// Update modifies an existing Actor (must have UID set).
func (c *ActorClient) Update(ctx context.Context, s *Actor) error {
	return c.conn.Update(ctx, s)
}

// Upsert inserts or updates a Actor, matching against predicates. If no
// predicates are provided, the first field tagged dgman:"upsert" wins.
func (c *ActorClient) Upsert(ctx context.Context, s *Actor, predicates ...string) error {
	return c.conn.Upsert(ctx, s, predicates...)
}

// Delete removes the Actor with the given UID.
func (c *ActorClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Query returns a query builder for Actor, allowing further refinement
// before execution.
func (c *ActorClient) Query(ctx context.Context) *ActorQuery {
	return NewActorQuery(ctx, c.conn)
}
