// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"github.com/matthewmcneely/modusgraph"
)

// Client is a top-level holder for per-entity schema-side clients bound to
// a single modusgraph.Client connection. It is a convenience layer over the
// per-entity New<Entity>Client(conn) constructors.
type Client struct {
	// GraphClient is the shared modusgraph.Client connection. It is exported
	// so callers can reach operations the typed clients do not wrap — for
	// example QueryRaw, DropAll, WithRetry, and Close.
	GraphClient   modusgraph.Client
	Actor         *ActorClient
	ContentRating *ContentRatingClient
	Country       *CountryClient
	Director      *DirectorClient
	Film          *FilmClient
	Genre         *GenreClient
	Location      *LocationClient
	Performance   *PerformanceClient
	Rating        *RatingClient
	Studio        *StudioClient
}

// NewClient binds conn to a Client whose per-entity sub-clients all share
// the same connection.
func NewClient(conn modusgraph.Client) *Client {
	c := &Client{GraphClient: conn}
	c.Actor = NewActorClient(conn)
	c.ContentRating = NewContentRatingClient(conn)
	c.Country = NewCountryClient(conn)
	c.Director = NewDirectorClient(conn)
	c.Film = NewFilmClient(conn)
	c.Genre = NewGenreClient(conn)
	c.Location = NewLocationClient(conn)
	c.Performance = NewPerformanceClient(conn)
	c.Rating = NewRatingClient(conn)
	c.Studio = NewStudioClient(conn)
	return c
}
