// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"github.com/matthewmcneely/modusgraph"
	"github.com/matthewmcneely/modusgraph/typed"
)

// Client is a top-level holder for per-entity typed clients bound to a single
// modusgraph.Client connection.
type Client struct {
	// GraphClient is the shared modusgraph.Client connection. It is exported
	// so callers can reach operations the typed clients do not wrap — for
	// example QueryRaw, DropAll, WithRetry, and Close.
	GraphClient   modusgraph.Client
	Actor         *typed.Client[Actor]
	ContentRating *typed.Client[ContentRating]
	Country       *typed.Client[Country]
	Director      *typed.Client[Director]
	Film          *typed.Client[Film]
	Genre         *typed.Client[Genre]
	Location      *typed.Client[Location]
	Performance   *typed.Client[Performance]
	Rating        *typed.Client[Rating]
	Studio        *typed.Client[Studio]
}

// NewClient binds conn to a Client whose per-entity typed clients all share
// the same connection.
func NewClient(conn modusgraph.Client) *Client {
	return &Client{
		GraphClient:   conn,
		Actor:         typed.NewClient[Actor](conn),
		ContentRating: typed.NewClient[ContentRating](conn),
		Country:       typed.NewClient[Country](conn),
		Director:      typed.NewClient[Director](conn),
		Film:          typed.NewClient[Film](conn),
		Genre:         typed.NewClient[Genre](conn),
		Location:      typed.NewClient[Location](conn),
		Performance:   typed.NewClient[Performance](conn),
		Rating:        typed.NewClient[Rating](conn),
		Studio:        typed.NewClient[Studio](conn),
	}
}
