// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// ContentRatingClient provides CRUD/query operations over ContentRating records.
// Takes and returns *ContentRating directly — no wrapper allocation.
type ContentRatingClient struct {
	conn modusgraph.Client
}

// NewContentRatingClient binds a ContentRatingClient to conn.
func NewContentRatingClient(conn modusgraph.Client) *ContentRatingClient {
	return &ContentRatingClient{conn: conn}
}

// Get loads the ContentRating with the given UID.
func (c *ContentRatingClient) Get(ctx context.Context, uid string) (*ContentRating, error) {
	var rec ContentRating
	if err := c.conn.Get(ctx, &rec, uid); err != nil {
		return nil, err
	}
	return &rec, nil
}

// Add inserts a new ContentRating.
func (c *ContentRatingClient) Add(ctx context.Context, s *ContentRating) error {
	return c.conn.Insert(ctx, s)
}

// Update modifies an existing ContentRating (must have UID set).
func (c *ContentRatingClient) Update(ctx context.Context, s *ContentRating) error {
	return c.conn.Update(ctx, s)
}

// Upsert inserts or updates a ContentRating, matching against predicates. If no
// predicates are provided, the first field tagged dgman:"upsert" wins.
func (c *ContentRatingClient) Upsert(ctx context.Context, s *ContentRating, predicates ...string) error {
	return c.conn.Upsert(ctx, s, predicates...)
}

// Delete removes the ContentRating with the given UID.
func (c *ContentRatingClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Query returns a query builder for ContentRating, allowing further refinement
// before execution.
func (c *ContentRatingClient) Query(ctx context.Context) *ContentRatingQuery {
	return NewContentRatingQuery(ctx, c.conn)
}
