// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// ContentRatingQuery is a fluent query builder for ContentRating records. Terminal
// methods (Nodes, First) execute the query against the underlying
// modusgraph.Client and populate raw *ContentRating results.
type ContentRatingQuery struct {
	ctx  context.Context
	conn modusgraph.Client
}

// NewContentRatingQuery constructs a query bound to ctx and conn. Callers
// usually obtain one via ContentRatingClient.Query rather than directly.
func NewContentRatingQuery(ctx context.Context, conn modusgraph.Client) *ContentRatingQuery {
	return &ContentRatingQuery{ctx: ctx, conn: conn}
}

// Nodes executes the query and decodes results into recs. recs must be a
// pointer to a []ContentRating or []*ContentRating slice.
func (q *ContentRatingQuery) Nodes(recs any) error {
	return q.conn.Query(q.ctx, &ContentRating{}).Nodes(recs)
}

// First runs the query with implicit Limit=1 and returns the first
// ContentRating record, or nil if the query yielded no rows.
func (q *ContentRatingQuery) First() (*ContentRating, error) {
	var recs []ContentRating
	if err := q.Nodes(&recs); err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, nil
	}
	return &recs[0], nil
}
