// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// CountryQuery is a fluent query builder for Country records. Terminal
// methods (Nodes, First) execute the query against the underlying
// modusgraph.Client and populate raw *Country results.
type CountryQuery struct {
	ctx  context.Context
	conn modusgraph.Client
}

// NewCountryQuery constructs a query bound to ctx and conn. Callers
// usually obtain one via CountryClient.Query rather than directly.
func NewCountryQuery(ctx context.Context, conn modusgraph.Client) *CountryQuery {
	return &CountryQuery{ctx: ctx, conn: conn}
}

// Nodes executes the query and decodes results into recs. recs must be a
// pointer to a []Country or []*Country slice.
func (q *CountryQuery) Nodes(recs any) error {
	return q.conn.Query(q.ctx, &Country{}).Nodes(recs)
}

// First runs the query with implicit Limit=1 and returns the first
// Country record, or nil if the query yielded no rows.
func (q *CountryQuery) First() (*Country, error) {
	var recs []Country
	if err := q.Nodes(&recs); err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, nil
	}
	return &recs[0], nil
}
