// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// CountryClient provides CRUD/query operations over Country records.
// Takes and returns *Country directly — no wrapper allocation.
type CountryClient struct {
	conn modusgraph.Client
}

// NewCountryClient binds a CountryClient to conn.
func NewCountryClient(conn modusgraph.Client) *CountryClient {
	return &CountryClient{conn: conn}
}

// Get loads the Country with the given UID.
func (c *CountryClient) Get(ctx context.Context, uid string) (*Country, error) {
	var rec Country
	if err := c.conn.Get(ctx, &rec, uid); err != nil {
		return nil, err
	}
	return &rec, nil
}

// Add inserts a new Country.
func (c *CountryClient) Add(ctx context.Context, s *Country) error {
	return c.conn.Insert(ctx, s)
}

// Update modifies an existing Country (must have UID set).
func (c *CountryClient) Update(ctx context.Context, s *Country) error {
	return c.conn.Update(ctx, s)
}

// Upsert inserts or updates a Country, matching against predicates. If no
// predicates are provided, the first field tagged dgman:"upsert" wins.
func (c *CountryClient) Upsert(ctx context.Context, s *Country, predicates ...string) error {
	return c.conn.Upsert(ctx, s, predicates...)
}

// Delete removes the Country with the given UID.
func (c *CountryClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Query returns a query builder for Country, allowing further refinement
// before execution.
func (c *CountryClient) Query(ctx context.Context) *CountryQuery {
	return NewCountryQuery(ctx, c.conn)
}
