// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// DirectorClient provides CRUD/query operations over Director records.
// Takes and returns *Director directly — no wrapper allocation.
type DirectorClient struct {
	conn modusgraph.Client
}

// NewDirectorClient binds a DirectorClient to conn.
func NewDirectorClient(conn modusgraph.Client) *DirectorClient {
	return &DirectorClient{conn: conn}
}

// Get loads the Director with the given UID.
func (c *DirectorClient) Get(ctx context.Context, uid string) (*Director, error) {
	var rec Director
	if err := c.conn.Get(ctx, &rec, uid); err != nil {
		return nil, err
	}
	return &rec, nil
}

// Add inserts a new Director.
func (c *DirectorClient) Add(ctx context.Context, s *Director) error {
	return c.conn.Insert(ctx, s)
}

// Update modifies an existing Director (must have UID set).
func (c *DirectorClient) Update(ctx context.Context, s *Director) error {
	return c.conn.Update(ctx, s)
}

// Upsert inserts or updates a Director, matching against predicates. If no
// predicates are provided, the first field tagged dgman:"upsert" wins.
func (c *DirectorClient) Upsert(ctx context.Context, s *Director, predicates ...string) error {
	return c.conn.Upsert(ctx, s, predicates...)
}

// Delete removes the Director with the given UID.
func (c *DirectorClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Query returns a query builder for Director, allowing further refinement
// before execution.
func (c *DirectorClient) Query(ctx context.Context) *DirectorQuery {
	return NewDirectorQuery(ctx, c.conn)
}
