// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// DirectorQuery is a fluent query builder for Director records. Terminal
// methods (Nodes, First) execute the query against the underlying
// modusgraph.Client and populate raw *Director results.
type DirectorQuery struct {
	ctx  context.Context
	conn modusgraph.Client
}

// NewDirectorQuery constructs a query bound to ctx and conn. Callers
// usually obtain one via DirectorClient.Query rather than directly.
func NewDirectorQuery(ctx context.Context, conn modusgraph.Client) *DirectorQuery {
	return &DirectorQuery{ctx: ctx, conn: conn}
}

// Nodes executes the query and decodes results into recs. recs must be a
// pointer to a []Director or []*Director slice.
func (q *DirectorQuery) Nodes(recs any) error {
	return q.conn.Query(q.ctx, &Director{}).Nodes(recs)
}

// First runs the query with implicit Limit=1 and returns the first
// Director record, or nil if the query yielded no rows.
func (q *DirectorQuery) First() (*Director, error) {
	var recs []Director
	if err := q.Nodes(&recs); err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, nil
	}
	return &recs[0], nil
}
