// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// FilmClient provides CRUD/query operations over Film records.
// Takes and returns *Film directly — no wrapper allocation.
type FilmClient struct {
	conn modusgraph.Client
}

// NewFilmClient binds a FilmClient to conn.
func NewFilmClient(conn modusgraph.Client) *FilmClient {
	return &FilmClient{conn: conn}
}

// Get loads the Film with the given UID.
func (c *FilmClient) Get(ctx context.Context, uid string) (*Film, error) {
	var rec Film
	if err := c.conn.Get(ctx, &rec, uid); err != nil {
		return nil, err
	}
	return &rec, nil
}

// Add inserts a new Film.
func (c *FilmClient) Add(ctx context.Context, s *Film) error {
	return c.conn.Insert(ctx, s)
}

// Update modifies an existing Film (must have UID set).
func (c *FilmClient) Update(ctx context.Context, s *Film) error {
	return c.conn.Update(ctx, s)
}

// Upsert inserts or updates a Film, matching against predicates. If no
// predicates are provided, the first field tagged dgman:"upsert" wins.
func (c *FilmClient) Upsert(ctx context.Context, s *Film, predicates ...string) error {
	return c.conn.Upsert(ctx, s, predicates...)
}

// Delete removes the Film with the given UID.
func (c *FilmClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Query returns a query builder for Film, allowing further refinement
// before execution.
func (c *FilmClient) Query(ctx context.Context) *FilmQuery {
	return NewFilmQuery(ctx, c.conn)
}
