// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// FilmQuery is a fluent query builder for Film records. Terminal
// methods (Nodes, First) execute the query against the underlying
// modusgraph.Client and populate raw *Film results.
type FilmQuery struct {
	ctx  context.Context
	conn modusgraph.Client
}

// NewFilmQuery constructs a query bound to ctx and conn. Callers
// usually obtain one via FilmClient.Query rather than directly.
func NewFilmQuery(ctx context.Context, conn modusgraph.Client) *FilmQuery {
	return &FilmQuery{ctx: ctx, conn: conn}
}

// Nodes executes the query and decodes results into recs. recs must be a
// pointer to a []Film or []*Film slice.
func (q *FilmQuery) Nodes(recs any) error {
	return q.conn.Query(q.ctx, &Film{}).Nodes(recs)
}

// First runs the query with implicit Limit=1 and returns the first
// Film record, or nil if the query yielded no rows.
func (q *FilmQuery) First() (*Film, error) {
	var recs []Film
	if err := q.Nodes(&recs); err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, nil
	}
	return &recs[0], nil
}
