// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// GenreClient provides CRUD/query operations over Genre records.
// Takes and returns *Genre directly — no wrapper allocation.
type GenreClient struct {
	conn modusgraph.Client
}

// NewGenreClient binds a GenreClient to conn.
func NewGenreClient(conn modusgraph.Client) *GenreClient {
	return &GenreClient{conn: conn}
}

// Get loads the Genre with the given UID.
func (c *GenreClient) Get(ctx context.Context, uid string) (*Genre, error) {
	var rec Genre
	if err := c.conn.Get(ctx, &rec, uid); err != nil {
		return nil, err
	}
	return &rec, nil
}

// Add inserts a new Genre.
func (c *GenreClient) Add(ctx context.Context, s *Genre) error {
	return c.conn.Insert(ctx, s)
}

// Update modifies an existing Genre (must have UID set).
func (c *GenreClient) Update(ctx context.Context, s *Genre) error {
	return c.conn.Update(ctx, s)
}

// Upsert inserts or updates a Genre, matching against predicates. If no
// predicates are provided, the first field tagged dgman:"upsert" wins.
func (c *GenreClient) Upsert(ctx context.Context, s *Genre, predicates ...string) error {
	return c.conn.Upsert(ctx, s, predicates...)
}

// Delete removes the Genre with the given UID.
func (c *GenreClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Query returns a query builder for Genre, allowing further refinement
// before execution.
func (c *GenreClient) Query(ctx context.Context) *GenreQuery {
	return NewGenreQuery(ctx, c.conn)
}
