// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// GenreQuery is a fluent query builder for Genre records. Terminal
// methods (Nodes, First) execute the query against the underlying
// modusgraph.Client and populate raw *Genre results.
type GenreQuery struct {
	ctx  context.Context
	conn modusgraph.Client
}

// NewGenreQuery constructs a query bound to ctx and conn. Callers
// usually obtain one via GenreClient.Query rather than directly.
func NewGenreQuery(ctx context.Context, conn modusgraph.Client) *GenreQuery {
	return &GenreQuery{ctx: ctx, conn: conn}
}

// Nodes executes the query and decodes results into recs. recs must be a
// pointer to a []Genre or []*Genre slice.
func (q *GenreQuery) Nodes(recs any) error {
	return q.conn.Query(q.ctx, &Genre{}).Nodes(recs)
}

// First runs the query with implicit Limit=1 and returns the first
// Genre record, or nil if the query yielded no rows.
func (q *GenreQuery) First() (*Genre, error) {
	var recs []Genre
	if err := q.Nodes(&recs); err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, nil
	}
	return &recs[0], nil
}
