// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// LocationClient provides CRUD/query operations over Location records.
// Takes and returns *Location directly — no wrapper allocation.
type LocationClient struct {
	conn modusgraph.Client
}

// NewLocationClient binds a LocationClient to conn.
func NewLocationClient(conn modusgraph.Client) *LocationClient {
	return &LocationClient{conn: conn}
}

// Get loads the Location with the given UID.
func (c *LocationClient) Get(ctx context.Context, uid string) (*Location, error) {
	var rec Location
	if err := c.conn.Get(ctx, &rec, uid); err != nil {
		return nil, err
	}
	return &rec, nil
}

// Add inserts a new Location.
func (c *LocationClient) Add(ctx context.Context, s *Location) error {
	return c.conn.Insert(ctx, s)
}

// Update modifies an existing Location (must have UID set).
func (c *LocationClient) Update(ctx context.Context, s *Location) error {
	return c.conn.Update(ctx, s)
}

// Upsert inserts or updates a Location, matching against predicates. If no
// predicates are provided, the first field tagged dgman:"upsert" wins.
func (c *LocationClient) Upsert(ctx context.Context, s *Location, predicates ...string) error {
	return c.conn.Upsert(ctx, s, predicates...)
}

// Delete removes the Location with the given UID.
func (c *LocationClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Query returns a query builder for Location, allowing further refinement
// before execution.
func (c *LocationClient) Query(ctx context.Context) *LocationQuery {
	return NewLocationQuery(ctx, c.conn)
}
