// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// LocationQuery is a fluent query builder for Location records. Terminal
// methods (Nodes, First) execute the query against the underlying
// modusgraph.Client and populate raw *Location results.
type LocationQuery struct {
	ctx  context.Context
	conn modusgraph.Client
}

// NewLocationQuery constructs a query bound to ctx and conn. Callers
// usually obtain one via LocationClient.Query rather than directly.
func NewLocationQuery(ctx context.Context, conn modusgraph.Client) *LocationQuery {
	return &LocationQuery{ctx: ctx, conn: conn}
}

// Nodes executes the query and decodes results into recs. recs must be a
// pointer to a []Location or []*Location slice.
func (q *LocationQuery) Nodes(recs any) error {
	return q.conn.Query(q.ctx, &Location{}).Nodes(recs)
}

// First runs the query with implicit Limit=1 and returns the first
// Location record, or nil if the query yielded no rows.
func (q *LocationQuery) First() (*Location, error) {
	var recs []Location
	if err := q.Nodes(&recs); err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, nil
	}
	return &recs[0], nil
}
