// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// PerformanceClient provides CRUD/query operations over Performance records.
// Takes and returns *Performance directly — no wrapper allocation.
type PerformanceClient struct {
	conn modusgraph.Client
}

// NewPerformanceClient binds a PerformanceClient to conn.
func NewPerformanceClient(conn modusgraph.Client) *PerformanceClient {
	return &PerformanceClient{conn: conn}
}

// Get loads the Performance with the given UID.
func (c *PerformanceClient) Get(ctx context.Context, uid string) (*Performance, error) {
	var rec Performance
	if err := c.conn.Get(ctx, &rec, uid); err != nil {
		return nil, err
	}
	return &rec, nil
}

// Add inserts a new Performance.
func (c *PerformanceClient) Add(ctx context.Context, s *Performance) error {
	return c.conn.Insert(ctx, s)
}

// Update modifies an existing Performance (must have UID set).
func (c *PerformanceClient) Update(ctx context.Context, s *Performance) error {
	return c.conn.Update(ctx, s)
}

// Upsert inserts or updates a Performance, matching against predicates. If no
// predicates are provided, the first field tagged dgman:"upsert" wins.
func (c *PerformanceClient) Upsert(ctx context.Context, s *Performance, predicates ...string) error {
	return c.conn.Upsert(ctx, s, predicates...)
}

// Delete removes the Performance with the given UID.
func (c *PerformanceClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Query returns a query builder for Performance, allowing further refinement
// before execution.
func (c *PerformanceClient) Query(ctx context.Context) *PerformanceQuery {
	return NewPerformanceQuery(ctx, c.conn)
}
