// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// PerformanceQuery is a fluent query builder for Performance records. Terminal
// methods (Nodes, First) execute the query against the underlying
// modusgraph.Client and populate raw *Performance results.
type PerformanceQuery struct {
	ctx  context.Context
	conn modusgraph.Client
}

// NewPerformanceQuery constructs a query bound to ctx and conn. Callers
// usually obtain one via PerformanceClient.Query rather than directly.
func NewPerformanceQuery(ctx context.Context, conn modusgraph.Client) *PerformanceQuery {
	return &PerformanceQuery{ctx: ctx, conn: conn}
}

// Nodes executes the query and decodes results into recs. recs must be a
// pointer to a []Performance or []*Performance slice.
func (q *PerformanceQuery) Nodes(recs any) error {
	return q.conn.Query(q.ctx, &Performance{}).Nodes(recs)
}

// First runs the query with implicit Limit=1 and returns the first
// Performance record, or nil if the query yielded no rows.
func (q *PerformanceQuery) First() (*Performance, error) {
	var recs []Performance
	if err := q.Nodes(&recs); err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, nil
	}
	return &recs[0], nil
}
