// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// RatingClient provides CRUD/query operations over Rating records.
// Takes and returns *Rating directly — no wrapper allocation.
type RatingClient struct {
	conn modusgraph.Client
}

// NewRatingClient binds a RatingClient to conn.
func NewRatingClient(conn modusgraph.Client) *RatingClient {
	return &RatingClient{conn: conn}
}

// Get loads the Rating with the given UID.
func (c *RatingClient) Get(ctx context.Context, uid string) (*Rating, error) {
	var rec Rating
	if err := c.conn.Get(ctx, &rec, uid); err != nil {
		return nil, err
	}
	return &rec, nil
}

// Add inserts a new Rating.
func (c *RatingClient) Add(ctx context.Context, s *Rating) error {
	return c.conn.Insert(ctx, s)
}

// Update modifies an existing Rating (must have UID set).
func (c *RatingClient) Update(ctx context.Context, s *Rating) error {
	return c.conn.Update(ctx, s)
}

// Upsert inserts or updates a Rating, matching against predicates. If no
// predicates are provided, the first field tagged dgman:"upsert" wins.
func (c *RatingClient) Upsert(ctx context.Context, s *Rating, predicates ...string) error {
	return c.conn.Upsert(ctx, s, predicates...)
}

// Delete removes the Rating with the given UID.
func (c *RatingClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Query returns a query builder for Rating, allowing further refinement
// before execution.
func (c *RatingClient) Query(ctx context.Context) *RatingQuery {
	return NewRatingQuery(ctx, c.conn)
}
