// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// RatingQuery is a fluent query builder for Rating records. Terminal
// methods (Nodes, First) execute the query against the underlying
// modusgraph.Client and populate raw *Rating results.
type RatingQuery struct {
	ctx  context.Context
	conn modusgraph.Client
}

// NewRatingQuery constructs a query bound to ctx and conn. Callers
// usually obtain one via RatingClient.Query rather than directly.
func NewRatingQuery(ctx context.Context, conn modusgraph.Client) *RatingQuery {
	return &RatingQuery{ctx: ctx, conn: conn}
}

// Nodes executes the query and decodes results into recs. recs must be a
// pointer to a []Rating or []*Rating slice.
func (q *RatingQuery) Nodes(recs any) error {
	return q.conn.Query(q.ctx, &Rating{}).Nodes(recs)
}

// First runs the query with implicit Limit=1 and returns the first
// Rating record, or nil if the query yielded no rows.
func (q *RatingQuery) First() (*Rating, error) {
	var recs []Rating
	if err := q.Nodes(&recs); err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, nil
	}
	return &recs[0], nil
}
