// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// StudioQuery is a fluent query builder for Studio records. Terminal
// methods (Nodes, First) execute the query against the underlying
// modusgraph.Client and populate raw *Studio results.
type StudioQuery struct {
	ctx  context.Context
	conn modusgraph.Client
}

// NewStudioQuery constructs a query bound to ctx and conn. Callers
// usually obtain one via StudioClient.Query rather than directly.
func NewStudioQuery(ctx context.Context, conn modusgraph.Client) *StudioQuery {
	return &StudioQuery{ctx: ctx, conn: conn}
}

// Nodes executes the query and decodes results into recs. recs must be a
// pointer to a []Studio or []*Studio slice.
func (q *StudioQuery) Nodes(recs any) error {
	return q.conn.Query(q.ctx, &Studio{}).Nodes(recs)
}

// First runs the query with implicit Limit=1 and returns the first
// Studio record, or nil if the query yielded no rows.
func (q *StudioQuery) First() (*Studio, error) {
	var recs []Studio
	if err := q.Nodes(&recs); err != nil {
		return nil, err
	}
	if len(recs) == 0 {
		return nil, nil
	}
	return &recs[0], nil
}
