// Code generated by modusGraphGen. DO NOT EDIT.

package schema

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// StudioClient provides CRUD/query operations over Studio records.
// Takes and returns *Studio directly — no wrapper allocation.
type StudioClient struct {
	conn modusgraph.Client
}

// NewStudioClient binds a StudioClient to conn.
func NewStudioClient(conn modusgraph.Client) *StudioClient {
	return &StudioClient{conn: conn}
}

// Get loads the Studio with the given UID.
func (c *StudioClient) Get(ctx context.Context, uid string) (*Studio, error) {
	var rec Studio
	if err := c.conn.Get(ctx, &rec, uid); err != nil {
		return nil, err
	}
	return &rec, nil
}

// Add inserts a new Studio.
func (c *StudioClient) Add(ctx context.Context, s *Studio) error {
	return c.conn.Insert(ctx, s)
}

// Update modifies an existing Studio (must have UID set).
func (c *StudioClient) Update(ctx context.Context, s *Studio) error {
	return c.conn.Update(ctx, s)
}

// Upsert inserts or updates a Studio, matching against predicates. If no
// predicates are provided, the first field tagged dgman:"upsert" wins.
func (c *StudioClient) Upsert(ctx context.Context, s *Studio, predicates ...string) error {
	return c.conn.Upsert(ctx, s, predicates...)
}

// Delete removes the Studio with the given UID.
func (c *StudioClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// Query returns a query builder for Studio, allowing further refinement
// before execution.
func (c *StudioClient) Query(ctx context.Context) *StudioQuery {
	return NewStudioQuery(ctx, c.conn)
}
