// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"encoding/json"
)

// DgraphMap converts the Studio to a map for Dgraph mutation.
// This enables persistence of private fields without requiring unsafe reflection.
func (e *Studio) DgraphMap() map[string]interface{} {
	m := make(map[string]interface{})
	if e.UID != "" {
		m["uid"] = e.UID
	}
	if len(e.DType) > 0 {
		m["dgraph.type"] = e.DType
	}
	if e.name != "" {
		m["name"] = e.name
	}
	if e.yearFounded != 0 {
		m["yearFounded"] = e.yearFounded
	}
	if e.revenue != 0 {
		m["revenue"] = e.revenue
	}
	if e.Founded != "" {
		m["founded"] = e.Founded
	}
	if e.founder != nil {
		m["founder"] = e.founder.DgraphMap()
	}
	if len(e.currentHead) > 0 {
		m["currentHead"] = e.currentHead[0].DgraphMap()
	}
	if len(e.ceo) > 0 && e.ceo[0] != nil {
		m["ceo"] = e.ceo[0].DgraphMap()
	}
	if len(e.homeBase) > 0 {
		m["homeBase"] = e.homeBase[0].DgraphMap()
	}
	if len(e.parentCompany) > 0 && e.parentCompany[0] != nil {
		m["parentCompany"] = e.parentCompany[0].DgraphMap()
	}
	if len(e.films) > 0 {
		s := make([]map[string]interface{}, 0, len(e.films))
		for i := range e.films {
			s = append(s, e.films[i].DgraphMap())
		}
		m["films"] = s
	}
	if len(e.advisors) > 0 {
		s := make([]map[string]interface{}, 0, len(e.advisors))
		for i := range e.advisors {
			if e.advisors[i] != nil {
				s = append(s, e.advisors[i].DgraphMap())
			}
		}
		m["advisors"] = s
	}
	if len(e.tags) > 0 {
		m["tags"] = e.tags
	}
	return m
}

// UnmarshalJSON implements custom JSON unmarshaling for Studio,
// allowing private fields to be populated from Dgraph query responses.
func (e *Studio) UnmarshalJSON(data []byte) error {
	type alias struct {
		UID           string      `json:"uid,omitempty"`
		DType         []string    `json:"dgraph.type,omitempty"`
		Name          string      `json:"name,omitempty"`
		YearFounded   int         `json:"yearFounded,omitempty"`
		Revenue       float64     `json:"revenue,omitempty"`
		Founded       string      `json:"founded,omitempty"`
		Founder       *Director   `json:"founder,omitempty"`
		CurrentHead   []Director  `json:"currentHead,omitempty"`
		Ceo           []*Director `json:"ceo,omitempty"`
		HomeBase      []Country   `json:"homeBase,omitempty"`
		ParentCompany []*Country  `json:"parentCompany,omitempty"`
		Films         []Film      `json:"films,omitempty"`
		Advisors      []*Director `json:"advisors,omitempty"`
		Tags          []string    `json:"tags,omitempty"`
	}
	var a alias
	if err := json.Unmarshal(data, &a); err != nil {
		return err
	}
	e.UID = a.UID
	e.DType = a.DType
	e.name = a.Name
	e.yearFounded = a.YearFounded
	e.revenue = a.Revenue
	e.Founded = a.Founded
	e.founder = a.Founder
	e.currentHead = a.CurrentHead
	e.ceo = a.Ceo
	e.homeBase = a.HomeBase
	e.parentCompany = a.ParentCompany
	e.films = a.Films
	e.advisors = a.Advisors
	e.tags = a.Tags
	return nil
}
