// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"slices"
)

// Name returns the name field.
func (e *Studio) Name() string {
	return e.name
}

// SetName sets the name field.
func (e *Studio) SetName(v string) {
	e.name = v
}

// Founder returns the founder singular edge, or nil if unset.
func (e *Studio) Founder() *Director {
	return e.founder
}

// SetFounder sets the founder singular edge. Pass nil to clear.
func (e *Studio) SetFounder(v *Director) {
	e.founder = v
}

// CurrentHead returns the currentHead singular edge, or nil if unset.
func (e *Studio) CurrentHead() *Director {
	if len(e.currentHead) == 0 {
		return nil
	}
	return &e.currentHead[0]
}

// SetCurrentHead sets the currentHead singular edge. Pass nil to clear.
func (e *Studio) SetCurrentHead(v *Director) {
	if v == nil {
		e.currentHead = nil
	} else {
		e.currentHead = []Director{*v}
	}
}

// Films returns the films edges.
func (e *Studio) Films() []Film {
	return e.films
}

// SetFilms replaces the films edges.
func (e *Studio) SetFilms(v []Film) {
	e.films = v
}

// AppendFilms appends one or more Film edges.
func (e *Studio) AppendFilms(v ...Film) {
	e.films = append(e.films, v...)
}

// RemoveFilms removes the edge with the given UID.
func (e *Studio) RemoveFilms(uid string) {
	e.films = slices.DeleteFunc(e.films, func(v Film) bool { return v.UID == uid })
}

// RemoveFilmsFunc removes edges matching the predicate.
func (e *Studio) RemoveFilmsFunc(fn func(Film) bool) {
	e.films = slices.DeleteFunc(e.films, fn)
}

// Tags returns the tags slice.
func (e *Studio) Tags() []string {
	return e.tags
}

// SetTags replaces the tags slice.
func (e *Studio) SetTags(v []string) {
	e.tags = v
}

// AppendTags appends one or more values to tags.
func (e *Studio) AppendTags(v ...string) {
	e.tags = append(e.tags, v...)
}

// RemoveTags removes the first occurrence of v from tags.
func (e *Studio) RemoveTags(v string) {
	for i, item := range e.tags {
		if item == v {
			e.tags = slices.Delete(e.tags, i, i+1)
			return
		}
	}
}

// RemoveTagsFunc removes values matching the predicate.
func (e *Studio) RemoveTagsFunc(fn func(string) bool) {
	e.tags = slices.DeleteFunc(e.tags, fn)
}
