// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"time"
)

// StudioOption is a functional option for configuring Studio mutations.
type StudioOption func(*Studio)

// WithStudioName sets the name field on a Studio.
func WithStudioName(v string) StudioOption {
	return func(e *Studio) {
		e.SetName(v)
	}
}

// WithStudioTags sets the tags field on a Studio.
func WithStudioTags(v []string) StudioOption {
	return func(e *Studio) {
		e.SetTags(v)
	}
}

// WithStudioYearFounded sets the yearFounded field on a Studio.
func WithStudioYearFounded(v int) StudioOption {
	return func(e *Studio) {
		e.SetYearFounded(v)
	}
}

// WithStudioRevenue sets the revenue field on a Studio.
func WithStudioRevenue(v float64) StudioOption {
	return func(e *Studio) {
		e.SetRevenue(v)
	}
}

// WithStudioActive sets the active field on a Studio.
func WithStudioActive(v bool) StudioOption {
	return func(e *Studio) {
		e.SetActive(v)
	}
}

// WithStudioCreatedAt sets the createdAt field on a Studio.
func WithStudioCreatedAt(v time.Time) StudioOption {
	return func(e *Studio) {
		e.SetCreatedAt(v)
	}
}

// WithStudioEmbedding sets the embedding field on a Studio.
func WithStudioEmbedding(v *dg.VectorFloat32) StudioOption {
	return func(e *Studio) {
		e.SetEmbedding(v)
	}
}

// WithStudioFounded sets the Founded field on a Studio.
func WithStudioFounded(v string) StudioOption {
	return func(e *Studio) {
		e.Founded = v
	}
}

// ApplyStudioOptions applies the given options to a Studio.
func ApplyStudioOptions(e *Studio, opts ...StudioOption) {
	for _, opt := range opts {
		opt(e)
	}
}
