// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// StudioQuery is a typed query builder for Studio entities.
type StudioQuery struct {
	conn      modusgraph.Client
	ctx       context.Context
	filter    string
	first     int
	offset    int
	orderBy   string
	orderDesc bool
}

// Query begins a new query for Studio entities.
func (c *StudioClient) Query(ctx context.Context) *StudioQuery {
	return &StudioQuery{conn: c.conn, ctx: ctx, first: defaultPageSize}
}

// Filter adds a DQL filter expression to the query.
func (q *StudioQuery) Filter(f string) *StudioQuery {
	q.filter = f
	return q
}

// OrderAsc sets ascending order on the given field.
func (q *StudioQuery) OrderAsc(field string) *StudioQuery {
	q.orderBy = field
	q.orderDesc = false
	return q
}

// OrderDesc sets descending order on the given field.
func (q *StudioQuery) OrderDesc(field string) *StudioQuery {
	q.orderBy = field
	q.orderDesc = true
	return q
}

// First limits the result to n nodes.
func (q *StudioQuery) First(n int) *StudioQuery {
	q.first = n
	return q
}

// Offset skips the first n nodes.
func (q *StudioQuery) Offset(n int) *StudioQuery {
	q.offset = n
	return q
}

// Exec executes the query and populates dst with the results.
func (q *StudioQuery) Exec(dst *[]Studio) error {
	dq := q.conn.Query(q.ctx, Studio{})
	if q.filter != "" {
		dq = dq.Filter(q.filter)
	}
	if q.first > 0 {
		dq = dq.First(q.first)
	}
	if q.offset > 0 {
		dq = dq.Offset(q.offset)
	}
	if q.orderBy != "" {
		if q.orderDesc {
			dq = dq.OrderDesc(q.orderBy)
		} else {
			dq = dq.OrderAsc(q.orderBy)
		}
	}
	return dq.Nodes(dst)
}

// ExecAndCount executes the query and returns both the results and total count.
func (q *StudioQuery) ExecAndCount(dst *[]Studio) (int, error) {
	dq := q.conn.Query(q.ctx, Studio{})
	if q.filter != "" {
		dq = dq.Filter(q.filter)
	}
	if q.first > 0 {
		dq = dq.First(q.first)
	}
	if q.offset > 0 {
		dq = dq.Offset(q.offset)
	}
	if q.orderBy != "" {
		if q.orderDesc {
			dq = dq.OrderDesc(q.orderBy)
		} else {
			dq = dq.OrderAsc(q.orderBy)
		}
	}
	return dq.NodesAndCount(dst)
}
