// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
)

// StudioClient provides typed CRUD operations for Studio entities.
type StudioClient struct {
	conn modusgraph.Client
}

// Get retrieves a single Studio by its UID.
func (c *StudioClient) Get(ctx context.Context, uid string) (*Studio, error) {
	var result Studio
	err := c.conn.Get(ctx, &result, uid)
	if err != nil {
		return nil, err
	}
	return &result, nil
}

// Add inserts a new Studio into the database.
func (c *StudioClient) Add(ctx context.Context, v *Studio) error {
	return c.conn.Insert(ctx, v)
}

// Update modifies an existing Studio in the database. The UID field must be set.
func (c *StudioClient) Update(ctx context.Context, v *Studio) error {
	return c.conn.Update(ctx, v)
}

// Delete removes the Studio with the given UID from the database.
func (c *StudioClient) Delete(ctx context.Context, uid string) error {
	return c.conn.Delete(ctx, []string{uid})
}

// List retrieves Studio entities with optional pagination.
func (c *StudioClient) List(ctx context.Context, opts ...PageOption) ([]Studio, error) {
	var results []Studio
	q := c.conn.Query(ctx, Studio{}).
		First(defaultPageSize)
	cfg := pageConfig{first: defaultPageSize}
	for _, opt := range opts {
		opt.applyPage(&cfg)
	}
	if cfg.first > 0 {
		q = q.First(cfg.first)
	}
	if cfg.offset > 0 {
		q = q.Offset(cfg.offset)
	}
	err := q.Nodes(&results)
	if err != nil {
		return nil, err
	}
	return results, nil
}
