// Code generated by modusGraphGen. DO NOT EDIT.

package main

import (
	"bufio"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/alecthomas/kong"
	"github.com/matthewmcneely/modusgraph"
	"github.com/matthewmcneely/modusgraph/schema"

	dg "github.com/dolan-in/dgman/v2"
)

// CLI is the root command parsed by Kong.
var CLI struct {
	Addr string `help:"Dgraph gRPC address." default:"dgraph://localhost:9080" env:"DGRAPH_ADDR"`
	Dir  string `help:"Local database directory (embedded mode, mutually exclusive with --addr)." env:"DGRAPH_DIR"`

	Query         QueryCmd         `cmd:"" help:"Execute a raw DQL query."`
	Actor         ActorCmd         `cmd:"" help:"Manage Actor entities."`
	ContentRating ContentRatingCmd `cmd:"" help:"Manage ContentRating entities."`
	Country       CountryCmd       `cmd:"" help:"Manage Country entities."`
	Director      DirectorCmd      `cmd:"" help:"Manage Director entities."`
	Film          FilmCmd          `cmd:"" help:"Manage Film entities."`
	Genre         GenreCmd         `cmd:"" help:"Manage Genre entities."`
	Location      LocationCmd      `cmd:"" help:"Manage Location entities."`
	Performance   PerformanceCmd   `cmd:"" help:"Manage Performance entities."`
	Rating        RatingCmd        `cmd:"" help:"Manage Rating entities."`
	Studio        StudioCmd        `cmd:"" help:"Manage Studio entities."`
}

// QueryCmd executes a raw DQL query against the database.
type QueryCmd struct {
	Query   string        `arg:"" optional:"" help:"DQL query string (reads stdin if omitted)."`
	Pretty  bool          `help:"Pretty-print JSON output." default:"true" negatable:""`
	Timeout time.Duration `help:"Query timeout." default:"30s"`
}

func (c *QueryCmd) Run(conn modusgraph.Client) error {
	query := c.Query
	if query == "" {
		// Read from stdin.
		reader := bufio.NewReader(os.Stdin)
		var sb strings.Builder
		for {
			line, err := reader.ReadString('\n')
			sb.WriteString(line)
			if err != nil {
				if err != io.EOF {
					return fmt.Errorf("reading stdin: %w", err)
				}
				break
			}
		}
		query = strings.TrimSpace(sb.String())
	}

	if query == "" {
		return fmt.Errorf("empty query: provide a DQL query as an argument or via stdin")
	}

	ctx, cancel := context.WithTimeout(context.Background(), c.Timeout)
	defer cancel()

	resp, err := conn.QueryRaw(ctx, query, nil)
	if err != nil {
		return err
	}

	if c.Pretty {
		var data any
		if err := json.Unmarshal(resp, &data); err != nil {
			return fmt.Errorf("parsing response: %w", err)
		}
		enc := json.NewEncoder(os.Stdout)
		enc.SetIndent("", "  ")
		return enc.Encode(data)
	}
	_, err = fmt.Println(string(resp))
	return err
}

// ActorCmd groups subcommands for Actor.
type ActorCmd struct {
	Get    ActorGetCmd    `cmd:"" help:"Get a Actor by UID."`
	List   ActorListCmd   `cmd:"" help:"List Actor entities."`
	Add    ActorAddCmd    `cmd:"" help:"Add a new Actor."`
	Delete ActorDeleteCmd `cmd:"" help:"Delete a Actor by UID."`
}

type ActorGetCmd struct {
	UID string `arg:"" required:"" help:"The UID of the Actor."`
}

func (c *ActorGetCmd) Run(client *schema.Client) error {
	result, err := client.Actor.Get(context.Background(), c.UID)
	if err != nil {
		return err
	}
	return printJSON(result)
}

type ActorListCmd struct{}

func (c *ActorListCmd) Run(client *schema.Client) error {
	var recs []schema.Actor
	if err := client.Actor.Query(context.Background()).Nodes(&recs); err != nil {
		return err
	}
	return printJSON(recs)
}

type ActorAddCmd struct {
	Name string `help:"Set Name." name:"name"`
}

func (c *ActorAddCmd) Run(client *schema.Client) error {
	e := &schema.Actor{}
	e.Name = c.Name
	if err := client.Actor.Add(context.Background(), e); err != nil {
		return err
	}
	return printJSON(e)
}

type ActorDeleteCmd struct {
	UID string `arg:"" required:"" help:"The UID to delete."`
}

func (c *ActorDeleteCmd) Run(client *schema.Client) error {
	return client.Actor.Delete(context.Background(), c.UID)
}

// ContentRatingCmd groups subcommands for ContentRating.
type ContentRatingCmd struct {
	Get    ContentRatingGetCmd    `cmd:"" help:"Get a ContentRating by UID."`
	List   ContentRatingListCmd   `cmd:"" help:"List ContentRating entities."`
	Add    ContentRatingAddCmd    `cmd:"" help:"Add a new ContentRating."`
	Delete ContentRatingDeleteCmd `cmd:"" help:"Delete a ContentRating by UID."`
}

type ContentRatingGetCmd struct {
	UID string `arg:"" required:"" help:"The UID of the ContentRating."`
}

func (c *ContentRatingGetCmd) Run(client *schema.Client) error {
	result, err := client.ContentRating.Get(context.Background(), c.UID)
	if err != nil {
		return err
	}
	return printJSON(result)
}

type ContentRatingListCmd struct{}

func (c *ContentRatingListCmd) Run(client *schema.Client) error {
	var recs []schema.ContentRating
	if err := client.ContentRating.Query(context.Background()).Nodes(&recs); err != nil {
		return err
	}
	return printJSON(recs)
}

type ContentRatingAddCmd struct {
	Name string `help:"Set Name." name:"name"`
}

func (c *ContentRatingAddCmd) Run(client *schema.Client) error {
	e := &schema.ContentRating{}
	e.Name = c.Name
	if err := client.ContentRating.Add(context.Background(), e); err != nil {
		return err
	}
	return printJSON(e)
}

type ContentRatingDeleteCmd struct {
	UID string `arg:"" required:"" help:"The UID to delete."`
}

func (c *ContentRatingDeleteCmd) Run(client *schema.Client) error {
	return client.ContentRating.Delete(context.Background(), c.UID)
}

// CountryCmd groups subcommands for Country.
type CountryCmd struct {
	Get    CountryGetCmd    `cmd:"" help:"Get a Country by UID."`
	List   CountryListCmd   `cmd:"" help:"List Country entities."`
	Add    CountryAddCmd    `cmd:"" help:"Add a new Country."`
	Delete CountryDeleteCmd `cmd:"" help:"Delete a Country by UID."`
}

type CountryGetCmd struct {
	UID string `arg:"" required:"" help:"The UID of the Country."`
}

func (c *CountryGetCmd) Run(client *schema.Client) error {
	result, err := client.Country.Get(context.Background(), c.UID)
	if err != nil {
		return err
	}
	return printJSON(result)
}

type CountryListCmd struct{}

func (c *CountryListCmd) Run(client *schema.Client) error {
	var recs []schema.Country
	if err := client.Country.Query(context.Background()).Nodes(&recs); err != nil {
		return err
	}
	return printJSON(recs)
}

type CountryAddCmd struct {
	Name string `help:"Set Name." name:"name"`
}

func (c *CountryAddCmd) Run(client *schema.Client) error {
	e := &schema.Country{}
	e.Name = c.Name
	if err := client.Country.Add(context.Background(), e); err != nil {
		return err
	}
	return printJSON(e)
}

type CountryDeleteCmd struct {
	UID string `arg:"" required:"" help:"The UID to delete."`
}

func (c *CountryDeleteCmd) Run(client *schema.Client) error {
	return client.Country.Delete(context.Background(), c.UID)
}

// DirectorCmd groups subcommands for Director.
type DirectorCmd struct {
	Get    DirectorGetCmd    `cmd:"" help:"Get a Director by UID."`
	List   DirectorListCmd   `cmd:"" help:"List Director entities."`
	Add    DirectorAddCmd    `cmd:"" help:"Add a new Director."`
	Delete DirectorDeleteCmd `cmd:"" help:"Delete a Director by UID."`
}

type DirectorGetCmd struct {
	UID string `arg:"" required:"" help:"The UID of the Director."`
}

func (c *DirectorGetCmd) Run(client *schema.Client) error {
	result, err := client.Director.Get(context.Background(), c.UID)
	if err != nil {
		return err
	}
	return printJSON(result)
}

type DirectorListCmd struct{}

func (c *DirectorListCmd) Run(client *schema.Client) error {
	var recs []schema.Director
	if err := client.Director.Query(context.Background()).Nodes(&recs); err != nil {
		return err
	}
	return printJSON(recs)
}

type DirectorAddCmd struct {
	Name string `help:"Set Name." name:"name"`
}

func (c *DirectorAddCmd) Run(client *schema.Client) error {
	e := &schema.Director{}
	e.Name = c.Name
	if err := client.Director.Add(context.Background(), e); err != nil {
		return err
	}
	return printJSON(e)
}

type DirectorDeleteCmd struct {
	UID string `arg:"" required:"" help:"The UID to delete."`
}

func (c *DirectorDeleteCmd) Run(client *schema.Client) error {
	return client.Director.Delete(context.Background(), c.UID)
}

// FilmCmd groups subcommands for Film.
type FilmCmd struct {
	Get    FilmGetCmd    `cmd:"" help:"Get a Film by UID."`
	List   FilmListCmd   `cmd:"" help:"List Film entities."`
	Add    FilmAddCmd    `cmd:"" help:"Add a new Film."`
	Delete FilmDeleteCmd `cmd:"" help:"Delete a Film by UID."`
}

type FilmGetCmd struct {
	UID string `arg:"" required:"" help:"The UID of the Film."`
}

func (c *FilmGetCmd) Run(client *schema.Client) error {
	result, err := client.Film.Get(context.Background(), c.UID)
	if err != nil {
		return err
	}
	return printJSON(result)
}

type FilmListCmd struct{}

func (c *FilmListCmd) Run(client *schema.Client) error {
	var recs []schema.Film
	if err := client.Film.Query(context.Background()).Nodes(&recs); err != nil {
		return err
	}
	return printJSON(recs)
}

type FilmAddCmd struct {
	Name               string `help:"Set Name." name:"name"`
	InitialReleaseDate string `help:"Set InitialReleaseDate." name:"initialreleasedate"`
	Tagline            string `help:"Set Tagline." name:"tagline"`
}

func (c *FilmAddCmd) Run(client *schema.Client) error {
	e := &schema.Film{}
	e.Name = c.Name
	if c.InitialReleaseDate != "" {
		parsed, err := time.Parse(time.RFC3339, c.InitialReleaseDate)
		if err != nil {
			return fmt.Errorf("invalid time for InitialReleaseDate: %w", err)
		}
		e.InitialReleaseDate = parsed
	}
	e.Tagline = c.Tagline
	if err := client.Film.Add(context.Background(), e); err != nil {
		return err
	}
	return printJSON(e)
}

type FilmDeleteCmd struct {
	UID string `arg:"" required:"" help:"The UID to delete."`
}

func (c *FilmDeleteCmd) Run(client *schema.Client) error {
	return client.Film.Delete(context.Background(), c.UID)
}

// GenreCmd groups subcommands for Genre.
type GenreCmd struct {
	Get    GenreGetCmd    `cmd:"" help:"Get a Genre by UID."`
	List   GenreListCmd   `cmd:"" help:"List Genre entities."`
	Add    GenreAddCmd    `cmd:"" help:"Add a new Genre."`
	Delete GenreDeleteCmd `cmd:"" help:"Delete a Genre by UID."`
}

type GenreGetCmd struct {
	UID string `arg:"" required:"" help:"The UID of the Genre."`
}

func (c *GenreGetCmd) Run(client *schema.Client) error {
	result, err := client.Genre.Get(context.Background(), c.UID)
	if err != nil {
		return err
	}
	return printJSON(result)
}

type GenreListCmd struct{}

func (c *GenreListCmd) Run(client *schema.Client) error {
	var recs []schema.Genre
	if err := client.Genre.Query(context.Background()).Nodes(&recs); err != nil {
		return err
	}
	return printJSON(recs)
}

type GenreAddCmd struct {
	Name string `help:"Set Name." name:"name"`
}

func (c *GenreAddCmd) Run(client *schema.Client) error {
	e := &schema.Genre{}
	e.Name = c.Name
	if err := client.Genre.Add(context.Background(), e); err != nil {
		return err
	}
	return printJSON(e)
}

type GenreDeleteCmd struct {
	UID string `arg:"" required:"" help:"The UID to delete."`
}

func (c *GenreDeleteCmd) Run(client *schema.Client) error {
	return client.Genre.Delete(context.Background(), c.UID)
}

// LocationCmd groups subcommands for Location.
type LocationCmd struct {
	Get    LocationGetCmd    `cmd:"" help:"Get a Location by UID."`
	List   LocationListCmd   `cmd:"" help:"List Location entities."`
	Add    LocationAddCmd    `cmd:"" help:"Add a new Location."`
	Delete LocationDeleteCmd `cmd:"" help:"Delete a Location by UID."`
}

type LocationGetCmd struct {
	UID string `arg:"" required:"" help:"The UID of the Location."`
}

func (c *LocationGetCmd) Run(client *schema.Client) error {
	result, err := client.Location.Get(context.Background(), c.UID)
	if err != nil {
		return err
	}
	return printJSON(result)
}

type LocationListCmd struct{}

func (c *LocationListCmd) Run(client *schema.Client) error {
	var recs []schema.Location
	if err := client.Location.Query(context.Background()).Nodes(&recs); err != nil {
		return err
	}
	return printJSON(recs)
}

type LocationAddCmd struct {
	Name  string `help:"Set Name." name:"name"`
	Email string `help:"Set Email." name:"email"`
}

func (c *LocationAddCmd) Run(client *schema.Client) error {
	e := &schema.Location{}
	e.Name = c.Name
	e.Email = c.Email
	if err := client.Location.Add(context.Background(), e); err != nil {
		return err
	}
	return printJSON(e)
}

type LocationDeleteCmd struct {
	UID string `arg:"" required:"" help:"The UID to delete."`
}

func (c *LocationDeleteCmd) Run(client *schema.Client) error {
	return client.Location.Delete(context.Background(), c.UID)
}

// PerformanceCmd groups subcommands for Performance.
type PerformanceCmd struct {
	Get    PerformanceGetCmd    `cmd:"" help:"Get a Performance by UID."`
	List   PerformanceListCmd   `cmd:"" help:"List Performance entities."`
	Add    PerformanceAddCmd    `cmd:"" help:"Add a new Performance."`
	Delete PerformanceDeleteCmd `cmd:"" help:"Delete a Performance by UID."`
}

type PerformanceGetCmd struct {
	UID string `arg:"" required:"" help:"The UID of the Performance."`
}

func (c *PerformanceGetCmd) Run(client *schema.Client) error {
	result, err := client.Performance.Get(context.Background(), c.UID)
	if err != nil {
		return err
	}
	return printJSON(result)
}

type PerformanceListCmd struct{}

func (c *PerformanceListCmd) Run(client *schema.Client) error {
	var recs []schema.Performance
	if err := client.Performance.Query(context.Background()).Nodes(&recs); err != nil {
		return err
	}
	return printJSON(recs)
}

type PerformanceAddCmd struct {
	CharacterNote string `help:"Set CharacterNote." name:"characternote"`
}

func (c *PerformanceAddCmd) Run(client *schema.Client) error {
	e := &schema.Performance{}
	e.CharacterNote = c.CharacterNote
	if err := client.Performance.Add(context.Background(), e); err != nil {
		return err
	}
	return printJSON(e)
}

type PerformanceDeleteCmd struct {
	UID string `arg:"" required:"" help:"The UID to delete."`
}

func (c *PerformanceDeleteCmd) Run(client *schema.Client) error {
	return client.Performance.Delete(context.Background(), c.UID)
}

// RatingCmd groups subcommands for Rating.
type RatingCmd struct {
	Get    RatingGetCmd    `cmd:"" help:"Get a Rating by UID."`
	List   RatingListCmd   `cmd:"" help:"List Rating entities."`
	Add    RatingAddCmd    `cmd:"" help:"Add a new Rating."`
	Delete RatingDeleteCmd `cmd:"" help:"Delete a Rating by UID."`
}

type RatingGetCmd struct {
	UID string `arg:"" required:"" help:"The UID of the Rating."`
}

func (c *RatingGetCmd) Run(client *schema.Client) error {
	result, err := client.Rating.Get(context.Background(), c.UID)
	if err != nil {
		return err
	}
	return printJSON(result)
}

type RatingListCmd struct{}

func (c *RatingListCmd) Run(client *schema.Client) error {
	var recs []schema.Rating
	if err := client.Rating.Query(context.Background()).Nodes(&recs); err != nil {
		return err
	}
	return printJSON(recs)
}

type RatingAddCmd struct {
	Name string `help:"Set Name." name:"name"`
}

func (c *RatingAddCmd) Run(client *schema.Client) error {
	e := &schema.Rating{}
	e.Name = c.Name
	if err := client.Rating.Add(context.Background(), e); err != nil {
		return err
	}
	return printJSON(e)
}

type RatingDeleteCmd struct {
	UID string `arg:"" required:"" help:"The UID to delete."`
}

func (c *RatingDeleteCmd) Run(client *schema.Client) error {
	return client.Rating.Delete(context.Background(), c.UID)
}

// StudioCmd groups subcommands for Studio.
type StudioCmd struct {
	Get    StudioGetCmd    `cmd:"" help:"Get a Studio by UID."`
	List   StudioListCmd   `cmd:"" help:"List Studio entities."`
	Add    StudioAddCmd    `cmd:"" help:"Add a new Studio."`
	Delete StudioDeleteCmd `cmd:"" help:"Delete a Studio by UID."`
}

type StudioGetCmd struct {
	UID string `arg:"" required:"" help:"The UID of the Studio."`
}

func (c *StudioGetCmd) Run(client *schema.Client) error {
	result, err := client.Studio.Get(context.Background(), c.UID)
	if err != nil {
		return err
	}
	return printJSON(result)
}

type StudioListCmd struct{}

func (c *StudioListCmd) Run(client *schema.Client) error {
	var recs []schema.Studio
	if err := client.Studio.Query(context.Background()).Nodes(&recs); err != nil {
		return err
	}
	return printJSON(recs)
}

type StudioAddCmd struct {
	Name        string  `help:"Set Name." name:"name"`
	YearFounded int     `help:"Set YearFounded." name:"yearfounded"`
	Revenue     float64 `help:"Set Revenue." name:"revenue"`
	Active      bool    `help:"Set Active." name:"active"`
	CreatedAt   string  `help:"Set CreatedAt." name:"createdat"`
}

func (c *StudioAddCmd) Run(client *schema.Client) error {
	e := &schema.Studio{}
	e.Name = c.Name
	e.YearFounded = c.YearFounded
	e.Revenue = c.Revenue
	e.Active = c.Active
	if c.CreatedAt != "" {
		parsed, err := time.Parse(time.RFC3339, c.CreatedAt)
		if err != nil {
			return fmt.Errorf("invalid time for CreatedAt: %w", err)
		}
		e.CreatedAt = parsed
	}
	if err := client.Studio.Add(context.Background(), e); err != nil {
		return err
	}
	return printJSON(e)
}

type StudioDeleteCmd struct {
	UID string `arg:"" required:"" help:"The UID to delete."`
}

func (c *StudioDeleteCmd) Run(client *schema.Client) error {
	return client.Studio.Delete(context.Background(), c.UID)
}

func printJSON(v any) error {
	enc := json.NewEncoder(os.Stdout)
	enc.SetIndent("", "  ")
	return enc.Encode(v)
}

func connectString() (string, error) {
	if CLI.Dir != "" {
		if CLI.Addr != "dgraph://localhost:9080" {
			return "", fmt.Errorf("--addr and --dir are mutually exclusive")
		}
		return fmt.Sprintf("file://%s", filepath.Clean(CLI.Dir)), nil
	}
	return CLI.Addr, nil
}

func main() {
	ctx := kong.Parse(&CLI,
		kong.Name("schema"),
		kong.Description("CLI for the schema data model."),
	)

	connStr, err := connectString()
	if err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
		os.Exit(1)
	}

	conn, err := modusgraph.NewClient(connStr,
		modusgraph.WithAutoSchema(true),
	)
	if err != nil {
		fmt.Fprintf(os.Stderr, "connect: %v\n", err)
		os.Exit(1)
	}
	defer conn.Close()

	client := schema.NewClient(conn)

	err = ctx.Run(conn, client)
	ctx.FatalIfErrorf(err)
}
