// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "github.com/mlwelles/modusGraphMoviesProject/schema"

// ActorQuery is the wrapper-side query builder. Composes over
// schema.ActorQuery; terminal methods wrap results before returning.
type ActorQuery struct {
	schemaQuery *schema.ActorQuery
}

// Nodes executes the query and returns wrapped Actor results.
func (q *ActorQuery) Nodes() ([]*Actor, error) {
	var recs []schema.Actor
	if err := q.schemaQuery.Nodes(&recs); err != nil {
		return nil, err
	}
	out := make([]*Actor, len(recs))
	for i := range recs {
		out[i] = WrapActor(&recs[i])
	}
	return out, nil
}

// First returns the first matching wrapper, or nil if no rows.
func (q *ActorQuery) First() (*Actor, error) {
	s, err := q.schemaQuery.First()
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, nil
	}
	return WrapActor(s), nil
}
