// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"iter"

	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// ActorQuery is the wrapper-side fluent query builder for Actor. Builder
// methods return *ActorQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type ActorQuery struct {
	typed *typed.Query[schema.Actor]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *ActorQuery) Filter(filter string, params ...any) *ActorQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *ActorQuery) OrderAsc(clause string) *ActorQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *ActorQuery) OrderDesc(clause string) *ActorQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *ActorQuery) Limit(n int) *ActorQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *ActorQuery) Offset(n int) *ActorQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *ActorQuery) After(uid string) *ActorQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *ActorQuery) Cascade(predicates ...string) *ActorQuery {
	q.typed.Cascade(predicates...)
	return q
}

// WhereFilms keeps only Actor records that have a actor.film
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *ActorQuery) WhereFilms(filter string, params ...any) *ActorQuery {
	q.typed.WhereEdge("actor.film", filter, params...)
	return q
}

// Nodes executes the query and returns wrapped Actor results.
func (q *ActorQuery) Nodes() ([]*Actor, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Actor, len(recs))
	for i := range recs {
		out[i] = WrapActor(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// wrapped Actor, or nil if no rows matched.
func (q *ActorQuery) First() (*Actor, error) {
	s, err := q.typed.First()
	if err != nil || s == nil {
		return nil, err
	}
	return WrapActor(s), nil
}

// IterNodes streams the query's results as wrapped Actor values, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *ActorQuery) IterNodes() iter.Seq2[*Actor, error] {
	return func(yield func(*Actor, error) bool) {
		for s, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(WrapActor(s), nil) {
				return
			}
		}
	}
}
