// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// ActorClient provides CRUD/query operations over Actor wrapper values.
// It composes over a typed.Client bound to the schema struct: reads wrap the
// schema result, writes forward the wrapper's backing struct.
type ActorClient struct {
	typed *typed.Client[schema.Actor]
}

// NewActorClient binds a ActorClient to conn.
func NewActorClient(conn modusgraph.Client) *ActorClient {
	return &ActorClient{typed: typed.NewClient[schema.Actor](conn)}
}

// Get loads the Actor with the given UID and returns it wrapped.
func (c *ActorClient) Get(ctx context.Context, uid string) (*Actor, error) {
	s, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapActor(s), nil
}

// Add inserts the schema struct backing w.
func (c *ActorClient) Add(ctx context.Context, w *Actor) error {
	return c.typed.Add(ctx, w.Unwrap())
}

// Update modifies the schema struct backing w (must have UID set).
func (c *ActorClient) Update(ctx context.Context, w *Actor) error {
	return c.typed.Update(ctx, w.Unwrap())
}

// Upsert inserts or updates the schema struct backing w, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *ActorClient) Upsert(ctx context.Context, w *Actor, predicates ...string) error {
	return c.typed.Upsert(ctx, w.Unwrap(), predicates...)
}

// Delete removes the Actor with the given UID.
func (c *ActorClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Actor.
func (c *ActorClient) Query(ctx context.Context) *ActorQuery {
	return &ActorQuery{typed: c.typed.Query(ctx)}
}
