// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Actor wraps a schema.Actor and exposes its data through methods.
// It embeds typed.Wrapper, which supplies Unwrap, JSON marshaling, and
// validation; the backing schema struct is reachable only via Unwrap().
type Actor struct {
	typed.Wrapper[schema.Actor]
}

// NewActor constructs a Actor with a fresh, empty schema struct, then
// applies the given options.
func NewActor(opts ...typed.Option[Actor]) *Actor {
	e := &Actor{Wrapper: typed.WrapValue(&schema.Actor{})}
	typed.Apply(e, opts...)
	return e
}

// WrapActor constructs a Actor backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive
// copy, so setters mutate the caller's struct.
func WrapActor(s *schema.Actor, opts ...typed.Option[Actor]) *Actor {
	e := &Actor{Wrapper: typed.WrapValue(s)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Actor) UID() string { return e.Unwrap().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Actor) SetUID(v string) { e.Unwrap().UID = v }

// DType returns the entity's dgraph type list.
func (e *Actor) DType() []string { return e.Unwrap().DType }

// SetDType sets the entity's dgraph type list.
func (e *Actor) SetDType(v []string) { e.Unwrap().DType = v }
