// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"
)

// WithActorName sets the name field on a *Actor.
func WithActorName(v string) typed.Option[Actor] {
	return func(e *Actor) { e.SetName(v) }
}
