// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"iter"
	"slices"

	"github.com/mlwelles/modusGraphMoviesProject/schema"
)

// Name returns the name field.
func (e *Actor) Name() string { return e.s.Name }

// SetName sets the name field.
func (e *Actor) SetName(v string) { e.s.Name = v }

// Films returns a freshly allocated slice of wrappers over each
// Performance in the multi-edge.
func (e *Actor) Films() []*Performance {
	out := make([]*Performance, len(e.s.Films))
	for i, x := range e.s.Films {
		out[i] = &Performance{s: x}
	}
	return out
}

// FilmsSeq returns an iterator over the wrapped Performances, avoiding
// the allocation in Films().
func (e *Actor) FilmsSeq() iter.Seq[*Performance] {
	return func(yield func(*Performance) bool) {
		for _, x := range e.s.Films {
			if !yield(&Performance{s: x}) {
				return
			}
		}
	}
}

// SetFilms replaces the multi-edge with the given items.
func (e *Actor) SetFilms(items ...*Performance) {
	e.s.Films = make([]*schema.Performance, len(items))
	for i, x := range items {
		e.s.Films[i] = x.s
	}
}

// AppendFilms appends items to the multi-edge.
func (e *Actor) AppendFilms(items ...*Performance) {
	for _, x := range items {
		e.s.Films = append(e.s.Films, x.s)
	}
}

// RemoveFilms removes elements with any of the given UIDs from the multi-edge.
func (e *Actor) RemoveFilms(uids ...string) {
	e.s.Films = slices.DeleteFunc(e.s.Films, func(x *schema.Performance) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}
