// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"

	"github.com/mlwelles/modusGraphMoviesProject/schema"
)

// ActorClient wraps a schema.ActorClient and exposes the same
// operations over wrapper types. Reads allocate a wrapper around the schema
// result; writes deref the wrapper's backing schema struct (w.s) and forward.
type ActorClient struct {
	schemaClient *schema.ActorClient
}

// NewActorClient binds a wrapper-side ActorClient to conn. Internally
// constructs a fresh schema.ActorClient on the same conn.
func NewActorClient(conn modusgraph.Client) *ActorClient {
	return &ActorClient{schemaClient: schema.NewActorClient(conn)}
}

// Get loads the Actor with the given UID and returns it wrapped.
func (c *ActorClient) Get(ctx context.Context, uid string) (*Actor, error) {
	s, err := c.schemaClient.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapActor(s), nil
}

// Add inserts the underlying schema struct from w.
func (c *ActorClient) Add(ctx context.Context, w *Actor) error {
	return c.schemaClient.Add(ctx, w.s)
}

// Update modifies the underlying schema struct from w (must have UID set).
func (c *ActorClient) Update(ctx context.Context, w *Actor) error {
	return c.schemaClient.Update(ctx, w.s)
}

// Upsert inserts or updates the underlying schema struct from w, matching
// against predicates. If no predicates are provided, the first field tagged
// dgraph:"upsert" wins.
func (c *ActorClient) Upsert(ctx context.Context, w *Actor, predicates ...string) error {
	return c.schemaClient.Upsert(ctx, w.s, predicates...)
}

// Delete removes the Actor with the given UID.
func (c *ActorClient) Delete(ctx context.Context, uid string) error {
	return c.schemaClient.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Actor.
func (c *ActorClient) Query(ctx context.Context) *ActorQuery {
	return &ActorQuery{schemaQuery: c.schemaClient.Query(ctx)}
}
