// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// ActorOption configures a *Actor. Applied at construction time via
// NewActor or WrapActor, or in bulk later via ApplyActorOptions.
type ActorOption func(*Actor)

// ApplyActorOptions applies a sequence of options to e in order.
func ApplyActorOptions(e *Actor, opts ...ActorOption) {
	for _, opt := range opts {
		opt(e)
	}
}

// WithActorName sets the name field on a *Actor.
func WithActorName(v string) ActorOption {
	return func(e *Actor) { e.SetName(v) }
}
