// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"
	"encoding/json"

	"github.com/go-playground/validator/v10"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Actor wraps a schema.Actor and exposes its data through
// methods. The backing schema struct is held in s; the only way to obtain
// it is via Unwrap(). All mutation goes through generated setters that
// write to s, so the wrapper has no state of its own.
type Actor struct {
	s *schema.Actor
}

// NewActor constructs a Actor with a fresh, empty schema struct inside,
// then applies the given options.
func NewActor(opts ...ActorOption) *Actor {
	e := &Actor{s: &schema.Actor{}}
	for _, opt := range opts {
		opt(e)
	}
	return e
}

// WrapActor constructs a Actor backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive copy.
// Mutations through Actor's setters write to s.
func WrapActor(s *schema.Actor, opts ...ActorOption) *Actor {
	e := &Actor{s: s}
	for _, opt := range opts {
		opt(e)
	}
	return e
}

// Unwrap returns the backing schema struct. modusgraph.Client uses this
// (via reflection) to substitute the schema struct when a wrapper is
// passed across the boundary.
func (e *Actor) Unwrap() *schema.Actor { return e.s }

// UID returns the entity's UID bookkeeping field.
func (e *Actor) UID() string { return e.s.UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Actor) SetUID(v string) { e.s.UID = v }

// DType returns the entity's dgraph type list.
func (e *Actor) DType() []string { return e.s.DType }

// SetDType sets the entity's dgraph type list.
func (e *Actor) SetDType(v []string) { e.s.DType = v }

// Validate runs v against the backing schema struct. The validator's tag
// processing sees the schema struct's public fields directly.
func (e *Actor) Validate(ctx context.Context, v *validator.Validate) error {
	return v.StructCtx(ctx, e.s)
}

// MarshalJSON delegates to the schema struct, whose public fields and
// json tags produce the correct serialization.
func (e *Actor) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.s)
}

// UnmarshalJSON lazily initializes the backing schema struct if needed,
// then delegates. Safe to call on a zero-value *Actor.
func (e *Actor) UnmarshalJSON(data []byte) error {
	if e.s == nil {
		e.s = &schema.Actor{}
	}
	return json.Unmarshal(data, e.s)
}
