// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph"

	"github.com/mlwelles/modusGraphMoviesProject/schema"
)

// Client is a top-level wrapper-side client. Holds a schema.Client
// internally and exposes per-entity wrapper sub-clients that compose over
// the schema-side clients.
type Client struct {
	schemaClient  *schema.Client
	Actor         *ActorClient
	ContentRating *ContentRatingClient
	Country       *CountryClient
	Director      *DirectorClient
	Film          *FilmClient
	Genre         *GenreClient
	Location      *LocationClient
	Performance   *PerformanceClient
	Rating        *RatingClient
	Studio        *StudioClient
}

// NewClient binds conn to a wrapper-side Client. The internal schema-side
// Client is constructed once and shared by all per-entity sub-clients.
func NewClient(conn modusgraph.Client) *Client {
	sc := schema.NewClient(conn)
	c := &Client{schemaClient: sc}
	c.Actor = &ActorClient{schemaClient: sc.Actor}
	c.ContentRating = &ContentRatingClient{schemaClient: sc.ContentRating}
	c.Country = &CountryClient{schemaClient: sc.Country}
	c.Director = &DirectorClient{schemaClient: sc.Director}
	c.Film = &FilmClient{schemaClient: sc.Film}
	c.Genre = &GenreClient{schemaClient: sc.Genre}
	c.Location = &LocationClient{schemaClient: sc.Location}
	c.Performance = &PerformanceClient{schemaClient: sc.Performance}
	c.Rating = &RatingClient{schemaClient: sc.Rating}
	c.Studio = &StudioClient{schemaClient: sc.Studio}
	return c
}
