// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph"
)

// Client is a top-level wrapper-side client. It holds a modusgraph.Client
// connection and exposes per-entity wrapper sub-clients that all share it.
type Client struct {
	conn          modusgraph.Client
	Actor         *ActorClient
	ContentRating *ContentRatingClient
	Country       *CountryClient
	Director      *DirectorClient
	Film          *FilmClient
	Genre         *GenreClient
	Location      *LocationClient
	Performance   *PerformanceClient
	Rating        *RatingClient
	Studio        *StudioClient
}

// NewClient binds conn to a wrapper-side Client.
func NewClient(conn modusgraph.Client) *Client {
	c := &Client{conn: conn}
	c.Actor = NewActorClient(conn)
	c.ContentRating = NewContentRatingClient(conn)
	c.Country = NewCountryClient(conn)
	c.Director = NewDirectorClient(conn)
	c.Film = NewFilmClient(conn)
	c.Genre = NewGenreClient(conn)
	c.Location = NewLocationClient(conn)
	c.Performance = NewPerformanceClient(conn)
	c.Rating = NewRatingClient(conn)
	c.Studio = NewStudioClient(conn)
	return c
}

// GraphClient returns the underlying modusgraph.Client connection. Use it for
// operations the typed clients do not wrap — for example QueryRaw, DropAll,
// WithRetry, and Close.
func (c *Client) GraphClient() modusgraph.Client {
	return c.conn
}
