// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"iter"

	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// ContentRatingQuery is the wrapper-side fluent query builder for ContentRating. Builder
// methods return *ContentRatingQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type ContentRatingQuery struct {
	typed *typed.Query[schema.ContentRating]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *ContentRatingQuery) Filter(filter string, params ...any) *ContentRatingQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *ContentRatingQuery) OrderAsc(clause string) *ContentRatingQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *ContentRatingQuery) OrderDesc(clause string) *ContentRatingQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *ContentRatingQuery) Limit(n int) *ContentRatingQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *ContentRatingQuery) Offset(n int) *ContentRatingQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *ContentRatingQuery) After(uid string) *ContentRatingQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *ContentRatingQuery) Cascade(predicates ...string) *ContentRatingQuery {
	q.typed.Cascade(predicates...)
	return q
}

// Nodes executes the query and returns wrapped ContentRating results.
func (q *ContentRatingQuery) Nodes() ([]*ContentRating, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*ContentRating, len(recs))
	for i := range recs {
		out[i] = WrapContentRating(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// wrapped ContentRating, or nil if no rows matched.
func (q *ContentRatingQuery) First() (*ContentRating, error) {
	s, err := q.typed.First()
	if err != nil || s == nil {
		return nil, err
	}
	return WrapContentRating(s), nil
}

// IterNodes streams the query's results as wrapped ContentRating values, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *ContentRatingQuery) IterNodes() iter.Seq2[*ContentRating, error] {
	return func(yield func(*ContentRating, error) bool) {
		for s, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(WrapContentRating(s), nil) {
				return
			}
		}
	}
}
