// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"

	"github.com/mlwelles/modusGraphMoviesProject/schema"
)

// ContentRatingClient wraps a schema.ContentRatingClient and exposes the same
// operations over wrapper types. Reads allocate a wrapper around the schema
// result; writes deref the wrapper's backing schema struct (w.s) and forward.
type ContentRatingClient struct {
	schemaClient *schema.ContentRatingClient
}

// NewContentRatingClient binds a wrapper-side ContentRatingClient to conn. Internally
// constructs a fresh schema.ContentRatingClient on the same conn.
func NewContentRatingClient(conn modusgraph.Client) *ContentRatingClient {
	return &ContentRatingClient{schemaClient: schema.NewContentRatingClient(conn)}
}

// Get loads the ContentRating with the given UID and returns it wrapped.
func (c *ContentRatingClient) Get(ctx context.Context, uid string) (*ContentRating, error) {
	s, err := c.schemaClient.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapContentRating(s), nil
}

// Add inserts the underlying schema struct from w.
func (c *ContentRatingClient) Add(ctx context.Context, w *ContentRating) error {
	return c.schemaClient.Add(ctx, w.s)
}

// Update modifies the underlying schema struct from w (must have UID set).
func (c *ContentRatingClient) Update(ctx context.Context, w *ContentRating) error {
	return c.schemaClient.Update(ctx, w.s)
}

// Upsert inserts or updates the underlying schema struct from w, matching
// against predicates. If no predicates are provided, the first field tagged
// dgraph:"upsert" wins.
func (c *ContentRatingClient) Upsert(ctx context.Context, w *ContentRating, predicates ...string) error {
	return c.schemaClient.Upsert(ctx, w.s, predicates...)
}

// Delete removes the ContentRating with the given UID.
func (c *ContentRatingClient) Delete(ctx context.Context, uid string) error {
	return c.schemaClient.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for ContentRating.
func (c *ContentRatingClient) Query(ctx context.Context) *ContentRatingQuery {
	return &ContentRatingQuery{schemaQuery: c.schemaClient.Query(ctx)}
}
