// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"

// ContentRatingQuery is the wrapper-side query builder. Composes over
// schema.ContentRatingQuery; terminal methods wrap results before returning.
type ContentRatingQuery struct {
	schemaQuery *schema.ContentRatingQuery
}

// Nodes executes the query and returns wrapped ContentRating results.
func (q *ContentRatingQuery) Nodes() ([]*ContentRating, error) {
	var recs []schema.ContentRating
	if err := q.schemaQuery.Nodes(&recs); err != nil {
		return nil, err
	}
	out := make([]*ContentRating, len(recs))
	for i := range recs {
		out[i] = WrapContentRating(&recs[i])
	}
	return out, nil
}

// First returns the first matching wrapper, or nil if no rows.
func (q *ContentRatingQuery) First() (*ContentRating, error) {
	s, err := q.schemaQuery.First()
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, nil
	}
	return WrapContentRating(s), nil
}
