// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"
)

// WithContentRatingName sets the name field on a *ContentRating.
func WithContentRatingName(v string) typed.Option[ContentRating] {
	return func(e *ContentRating) { e.SetName(v) }
}
