// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// ContentRating wraps a schema.ContentRating and exposes its data through methods.
// It embeds typed.Wrapper, which supplies Unwrap, JSON marshaling, and
// validation; the backing schema struct is reachable only via Unwrap().
type ContentRating struct {
	typed.Wrapper[schema.ContentRating]
}

// NewContentRating constructs a ContentRating with a fresh, empty schema struct, then
// applies the given options.
func NewContentRating(opts ...typed.Option[ContentRating]) *ContentRating {
	e := &ContentRating{Wrapper: typed.WrapValue(&schema.ContentRating{})}
	typed.Apply(e, opts...)
	return e
}

// WrapContentRating constructs a ContentRating backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive
// copy, so setters mutate the caller's struct.
func WrapContentRating(s *schema.ContentRating, opts ...typed.Option[ContentRating]) *ContentRating {
	e := &ContentRating{Wrapper: typed.WrapValue(s)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *ContentRating) UID() string { return e.Unwrap().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *ContentRating) SetUID(v string) { e.Unwrap().UID = v }

// DType returns the entity's dgraph type list.
func (e *ContentRating) DType() []string { return e.Unwrap().DType }

// SetDType sets the entity's dgraph type list.
func (e *ContentRating) SetDType(v []string) { e.Unwrap().DType = v }
