// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"iter"
	"slices"

	"github.com/mlwelles/modusGraphMoviesProject/schema"
)

// Name returns the name field.
func (e *Country) Name() string { return e.s.Name }

// SetName sets the name field.
func (e *Country) SetName(v string) { e.s.Name = v }

// Films returns a freshly allocated slice of wrappers over each
// Film in the multi-edge.
func (e *Country) Films() []*Film {
	out := make([]*Film, len(e.s.Films))
	for i, x := range e.s.Films {
		out[i] = &Film{s: x}
	}
	return out
}

// FilmsSeq returns an iterator over the wrapped Films, avoiding
// the allocation in Films().
func (e *Country) FilmsSeq() iter.Seq[*Film] {
	return func(yield func(*Film) bool) {
		for _, x := range e.s.Films {
			if !yield(&Film{s: x}) {
				return
			}
		}
	}
}

// SetFilms replaces the multi-edge with the given items.
func (e *Country) SetFilms(items ...*Film) {
	e.s.Films = make([]*schema.Film, len(items))
	for i, x := range items {
		e.s.Films[i] = x.s
	}
}

// AppendFilms appends items to the multi-edge.
func (e *Country) AppendFilms(items ...*Film) {
	for _, x := range items {
		e.s.Films = append(e.s.Films, x.s)
	}
}

// RemoveFilms removes elements with any of the given UIDs from the multi-edge.
func (e *Country) RemoveFilms(uids ...string) {
	e.s.Films = slices.DeleteFunc(e.s.Films, func(x *schema.Film) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}
