// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Country wraps a schema.Country and exposes its data through methods.
// It embeds typed.Wrapper, which supplies Unwrap, JSON marshaling, and
// validation; the backing schema struct is reachable only via Unwrap().
type Country struct {
	typed.Wrapper[schema.Country]
}

// NewCountry constructs a Country with a fresh, empty schema struct, then
// applies the given options.
func NewCountry(opts ...typed.Option[Country]) *Country {
	e := &Country{Wrapper: typed.WrapValue(&schema.Country{})}
	typed.Apply(e, opts...)
	return e
}

// WrapCountry constructs a Country backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive
// copy, so setters mutate the caller's struct.
func WrapCountry(s *schema.Country, opts ...typed.Option[Country]) *Country {
	e := &Country{Wrapper: typed.WrapValue(s)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Country) UID() string { return e.Unwrap().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Country) SetUID(v string) { e.Unwrap().UID = v }

// DType returns the entity's dgraph type list.
func (e *Country) DType() []string { return e.Unwrap().DType }

// SetDType sets the entity's dgraph type list.
func (e *Country) SetDType(v []string) { e.Unwrap().DType = v }
