// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"

// CountryQuery is the wrapper-side query builder. Composes over
// schema.CountryQuery; terminal methods wrap results before returning.
type CountryQuery struct {
	schemaQuery *schema.CountryQuery
}

// Nodes executes the query and returns wrapped Country results.
func (q *CountryQuery) Nodes() ([]*Country, error) {
	var recs []schema.Country
	if err := q.schemaQuery.Nodes(&recs); err != nil {
		return nil, err
	}
	out := make([]*Country, len(recs))
	for i := range recs {
		out[i] = WrapCountry(&recs[i])
	}
	return out, nil
}

// First returns the first matching wrapper, or nil if no rows.
func (q *CountryQuery) First() (*Country, error) {
	s, err := q.schemaQuery.First()
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, nil
	}
	return WrapCountry(s), nil
}
