// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// CountryOption configures a *Country. Applied at construction time via
// NewCountry or WrapCountry, or in bulk later via ApplyCountryOptions.
type CountryOption func(*Country)

// ApplyCountryOptions applies a sequence of options to e in order.
func ApplyCountryOptions(e *Country, opts ...CountryOption) {
	for _, opt := range opts {
		opt(e)
	}
}

// WithCountryName sets the name field on a *Country.
func WithCountryName(v string) CountryOption {
	return func(e *Country) { e.SetName(v) }
}
