// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// CountryClient provides CRUD/query operations over Country wrapper values.
// It composes over a typed.Client bound to the schema struct: reads wrap the
// schema result, writes forward the wrapper's backing struct.
type CountryClient struct {
	typed *typed.Client[schema.Country]
}

// NewCountryClient binds a CountryClient to conn.
func NewCountryClient(conn modusgraph.Client) *CountryClient {
	return &CountryClient{typed: typed.NewClient[schema.Country](conn)}
}

// Get loads the Country with the given UID and returns it wrapped.
func (c *CountryClient) Get(ctx context.Context, uid string) (*Country, error) {
	s, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapCountry(s), nil
}

// Add inserts the schema struct backing w.
func (c *CountryClient) Add(ctx context.Context, w *Country) error {
	return c.typed.Add(ctx, w.Unwrap())
}

// Update modifies the schema struct backing w (must have UID set).
func (c *CountryClient) Update(ctx context.Context, w *Country) error {
	return c.typed.Update(ctx, w.Unwrap())
}

// Upsert inserts or updates the schema struct backing w, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *CountryClient) Upsert(ctx context.Context, w *Country, predicates ...string) error {
	return c.typed.Upsert(ctx, w.Unwrap(), predicates...)
}

// Delete removes the Country with the given UID.
func (c *CountryClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Country.
func (c *CountryClient) Query(ctx context.Context) *CountryQuery {
	return &CountryQuery{typed: c.typed.Query(ctx)}
}
