// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"iter"

	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// CountryQuery is the wrapper-side fluent query builder for Country. Builder
// methods return *CountryQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type CountryQuery struct {
	typed *typed.Query[schema.Country]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *CountryQuery) Filter(filter string, params ...any) *CountryQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *CountryQuery) OrderAsc(clause string) *CountryQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *CountryQuery) OrderDesc(clause string) *CountryQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *CountryQuery) Limit(n int) *CountryQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *CountryQuery) Offset(n int) *CountryQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *CountryQuery) After(uid string) *CountryQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *CountryQuery) Cascade(predicates ...string) *CountryQuery {
	q.typed.Cascade(predicates...)
	return q
}

// Nodes executes the query and returns wrapped Country results.
func (q *CountryQuery) Nodes() ([]*Country, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Country, len(recs))
	for i := range recs {
		out[i] = WrapCountry(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// wrapped Country, or nil if no rows matched.
func (q *CountryQuery) First() (*Country, error) {
	s, err := q.typed.First()
	if err != nil || s == nil {
		return nil, err
	}
	return WrapCountry(s), nil
}

// IterNodes streams the query's results as wrapped Country values, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *CountryQuery) IterNodes() iter.Seq2[*Country, error] {
	return func(yield func(*Country, error) bool) {
		for s, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(WrapCountry(s), nil) {
				return
			}
		}
	}
}
