// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"
)

// WithCountryName sets the name field on a *Country.
func WithCountryName(v string) typed.Option[Country] {
	return func(e *Country) { e.SetName(v) }
}
