// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"
)

// WithDirectorName sets the name field on a *Director.
func WithDirectorName(v string) typed.Option[Director] {
	return func(e *Director) { e.SetName(v) }
}
