// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// DirectorClient provides CRUD/query operations over Director wrapper values.
// It composes over a typed.Client bound to the schema struct: reads wrap the
// schema result, writes forward the wrapper's backing struct.
type DirectorClient struct {
	typed *typed.Client[schema.Director]
}

// NewDirectorClient binds a DirectorClient to conn.
func NewDirectorClient(conn modusgraph.Client) *DirectorClient {
	return &DirectorClient{typed: typed.NewClient[schema.Director](conn)}
}

// Get loads the Director with the given UID and returns it wrapped.
func (c *DirectorClient) Get(ctx context.Context, uid string) (*Director, error) {
	s, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapDirector(s), nil
}

// Add inserts the schema struct backing w.
func (c *DirectorClient) Add(ctx context.Context, w *Director) error {
	return c.typed.Add(ctx, w.Unwrap())
}

// Update modifies the schema struct backing w (must have UID set).
func (c *DirectorClient) Update(ctx context.Context, w *Director) error {
	return c.typed.Update(ctx, w.Unwrap())
}

// Upsert inserts or updates the schema struct backing w, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *DirectorClient) Upsert(ctx context.Context, w *Director, predicates ...string) error {
	return c.typed.Upsert(ctx, w.Unwrap(), predicates...)
}

// Delete removes the Director with the given UID.
func (c *DirectorClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Director.
func (c *DirectorClient) Query(ctx context.Context) *DirectorQuery {
	return &DirectorQuery{typed: c.typed.Query(ctx)}
}
