// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"

	"github.com/mlwelles/modusGraphMoviesProject/schema"
)

// DirectorClient wraps a schema.DirectorClient and exposes the same
// operations over wrapper types. Reads allocate a wrapper around the schema
// result; writes deref the wrapper's backing schema struct (w.s) and forward.
type DirectorClient struct {
	schemaClient *schema.DirectorClient
}

// NewDirectorClient binds a wrapper-side DirectorClient to conn. Internally
// constructs a fresh schema.DirectorClient on the same conn.
func NewDirectorClient(conn modusgraph.Client) *DirectorClient {
	return &DirectorClient{schemaClient: schema.NewDirectorClient(conn)}
}

// Get loads the Director with the given UID and returns it wrapped.
func (c *DirectorClient) Get(ctx context.Context, uid string) (*Director, error) {
	s, err := c.schemaClient.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapDirector(s), nil
}

// Add inserts the underlying schema struct from w.
func (c *DirectorClient) Add(ctx context.Context, w *Director) error {
	return c.schemaClient.Add(ctx, w.s)
}

// Update modifies the underlying schema struct from w (must have UID set).
func (c *DirectorClient) Update(ctx context.Context, w *Director) error {
	return c.schemaClient.Update(ctx, w.s)
}

// Upsert inserts or updates the underlying schema struct from w, matching
// against predicates. If no predicates are provided, the first field tagged
// dgraph:"upsert" wins.
func (c *DirectorClient) Upsert(ctx context.Context, w *Director, predicates ...string) error {
	return c.schemaClient.Upsert(ctx, w.s, predicates...)
}

// Delete removes the Director with the given UID.
func (c *DirectorClient) Delete(ctx context.Context, uid string) error {
	return c.schemaClient.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Director.
func (c *DirectorClient) Query(ctx context.Context) *DirectorQuery {
	return &DirectorQuery{schemaQuery: c.schemaClient.Query(ctx)}
}
