// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Director wraps a schema.Director and exposes its data through methods.
// It embeds typed.Wrapper, which supplies Unwrap, JSON marshaling, and
// validation; the backing schema struct is reachable only via Unwrap().
type Director struct {
	typed.Wrapper[schema.Director]
}

// NewDirector constructs a Director with a fresh, empty schema struct, then
// applies the given options.
func NewDirector(opts ...typed.Option[Director]) *Director {
	e := &Director{Wrapper: typed.WrapValue(&schema.Director{})}
	typed.Apply(e, opts...)
	return e
}

// WrapDirector constructs a Director backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive
// copy, so setters mutate the caller's struct.
func WrapDirector(s *schema.Director, opts ...typed.Option[Director]) *Director {
	e := &Director{Wrapper: typed.WrapValue(s)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Director) UID() string { return e.Unwrap().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Director) SetUID(v string) { e.Unwrap().UID = v }

// DType returns the entity's dgraph type list.
func (e *Director) DType() []string { return e.Unwrap().DType }

// SetDType sets the entity's dgraph type list.
func (e *Director) SetDType(v []string) { e.Unwrap().DType = v }
