// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// DirectorQuery is the wrapper-side fluent query builder for Director. Builder
// methods return *DirectorQuery for chaining; terminal methods (Nodes, First)
// execute the query and wrap results.
type DirectorQuery struct {
	typed *typed.Query[schema.Director]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *DirectorQuery) Filter(filter string, params ...any) *DirectorQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *DirectorQuery) OrderAsc(clause string) *DirectorQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *DirectorQuery) OrderDesc(clause string) *DirectorQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *DirectorQuery) Limit(n int) *DirectorQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *DirectorQuery) Offset(n int) *DirectorQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *DirectorQuery) After(uid string) *DirectorQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *DirectorQuery) Cascade(predicates ...string) *DirectorQuery {
	q.typed.Cascade(predicates...)
	return q
}

// Nodes executes the query and returns wrapped Director results.
func (q *DirectorQuery) Nodes() ([]*Director, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Director, len(recs))
	for i := range recs {
		out[i] = WrapDirector(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// wrapped Director, or nil if no rows matched.
func (q *DirectorQuery) First() (*Director, error) {
	s, err := q.typed.First()
	if err != nil || s == nil {
		return nil, err
	}
	return WrapDirector(s), nil
}
