// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "github.com/mlwelles/modusGraphMoviesProject/schema"

// DirectorQuery is the wrapper-side query builder. Composes over
// schema.DirectorQuery; terminal methods wrap results before returning.
type DirectorQuery struct {
	schemaQuery *schema.DirectorQuery
}

// Nodes executes the query and returns wrapped Director results.
func (q *DirectorQuery) Nodes() ([]*Director, error) {
	var recs []schema.Director
	if err := q.schemaQuery.Nodes(&recs); err != nil {
		return nil, err
	}
	out := make([]*Director, len(recs))
	for i := range recs {
		out[i] = WrapDirector(&recs[i])
	}
	return out, nil
}

// First returns the first matching wrapper, or nil if no rows.
func (q *DirectorQuery) First() (*Director, error) {
	s, err := q.schemaQuery.First()
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, nil
	}
	return WrapDirector(s), nil
}
