// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// FilmQuery is the wrapper-side fluent query builder for Film. Builder
// methods return *FilmQuery for chaining; terminal methods (Nodes, First)
// execute the query and wrap results.
type FilmQuery struct {
	typed *typed.Query[schema.Film]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *FilmQuery) Filter(filter string, params ...any) *FilmQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *FilmQuery) OrderAsc(clause string) *FilmQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *FilmQuery) OrderDesc(clause string) *FilmQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *FilmQuery) Limit(n int) *FilmQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *FilmQuery) Offset(n int) *FilmQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *FilmQuery) After(uid string) *FilmQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *FilmQuery) Cascade(predicates ...string) *FilmQuery {
	q.typed.Cascade(predicates...)
	return q
}

// Nodes executes the query and returns wrapped Film results.
func (q *FilmQuery) Nodes() ([]*Film, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Film, len(recs))
	for i := range recs {
		out[i] = WrapFilm(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// wrapped Film, or nil if no rows matched.
func (q *FilmQuery) First() (*Film, error) {
	s, err := q.typed.First()
	if err != nil || s == nil {
		return nil, err
	}
	return WrapFilm(s), nil
}
