// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Film wraps a schema.Film and exposes its data through methods.
// It embeds typed.Wrapper, which supplies Unwrap, JSON marshaling, and
// validation; the backing schema struct is reachable only via Unwrap().
type Film struct {
	typed.Wrapper[schema.Film]
}

// NewFilm constructs a Film with a fresh, empty schema struct, then
// applies the given options.
func NewFilm(opts ...typed.Option[Film]) *Film {
	e := &Film{Wrapper: typed.WrapValue(&schema.Film{})}
	typed.Apply(e, opts...)
	return e
}

// WrapFilm constructs a Film backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive
// copy, so setters mutate the caller's struct.
func WrapFilm(s *schema.Film, opts ...typed.Option[Film]) *Film {
	e := &Film{Wrapper: typed.WrapValue(s)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Film) UID() string { return e.Unwrap().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Film) SetUID(v string) { e.Unwrap().UID = v }

// DType returns the entity's dgraph type list.
func (e *Film) DType() []string { return e.Unwrap().DType }

// SetDType sets the entity's dgraph type list.
func (e *Film) SetDType(v []string) { e.Unwrap().DType = v }
