// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"iter"

	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// FilmQuery is the wrapper-side fluent query builder for Film. Builder
// methods return *FilmQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type FilmQuery struct {
	typed *typed.Query[schema.Film]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *FilmQuery) Filter(filter string, params ...any) *FilmQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *FilmQuery) OrderAsc(clause string) *FilmQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *FilmQuery) OrderDesc(clause string) *FilmQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *FilmQuery) Limit(n int) *FilmQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *FilmQuery) Offset(n int) *FilmQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *FilmQuery) After(uid string) *FilmQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *FilmQuery) Cascade(predicates ...string) *FilmQuery {
	q.typed.Cascade(predicates...)
	return q
}

// WhereGenres keeps only Film records that have a genre
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereGenres(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("genre", filter, params...)
	return q
}

// WhereCountries keeps only Film records that have a country
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereCountries(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("country", filter, params...)
	return q
}

// WhereRatings keeps only Film records that have a rating
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereRatings(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("rating", filter, params...)
	return q
}

// WhereContentRatings keeps only Film records that have a rated
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereContentRatings(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("rated", filter, params...)
	return q
}

// WhereStarring keeps only Film records that have a starring
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereStarring(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("starring", filter, params...)
	return q
}

// WhereDirectors keeps only Film records that have a directors
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *FilmQuery) WhereDirectors(filter string, params ...any) *FilmQuery {
	q.typed.WhereEdge("directors", filter, params...)
	return q
}

// Nodes executes the query and returns wrapped Film results.
func (q *FilmQuery) Nodes() ([]*Film, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Film, len(recs))
	for i := range recs {
		out[i] = WrapFilm(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// wrapped Film, or nil if no rows matched.
func (q *FilmQuery) First() (*Film, error) {
	s, err := q.typed.First()
	if err != nil || s == nil {
		return nil, err
	}
	return WrapFilm(s), nil
}

// IterNodes streams the query's results as wrapped Film values, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *FilmQuery) IterNodes() iter.Seq2[*Film, error] {
	return func(yield func(*Film, error) bool) {
		for s, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(WrapFilm(s), nil) {
				return
			}
		}
	}
}
