// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"time"
)

// WithFilmName sets the name field on a *Film.
func WithFilmName(v string) typed.Option[Film] {
	return func(e *Film) { e.SetName(v) }
}

// WithFilmInitialReleaseDate sets the initialReleaseDate field on a *Film.
func WithFilmInitialReleaseDate(v time.Time) typed.Option[Film] {
	return func(e *Film) { e.SetInitialReleaseDate(v) }
}

// WithFilmTagline sets the tagline field on a *Film.
func WithFilmTagline(v string) typed.Option[Film] {
	return func(e *Film) { e.SetTagline(v) }
}
