// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// FilmClient wraps a schema.FilmClient and exposes the same
// operations over wrapper types. Reads allocate a wrapper around the schema
// result; writes deref the wrapper's backing schema struct (w.s) and forward.
type FilmClient struct {
	schemaClient *schema.FilmClient
}

// NewFilmClient binds a wrapper-side FilmClient to conn. Internally
// constructs a fresh schema.FilmClient on the same conn.
func NewFilmClient(conn modusgraph.Client) *FilmClient {
	return &FilmClient{schemaClient: schema.NewFilmClient(conn)}
}

// Get loads the Film with the given UID and returns it wrapped.
func (c *FilmClient) Get(ctx context.Context, uid string) (*Film, error) {
	s, err := c.schemaClient.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapFilm(s), nil
}

// Add inserts the underlying schema struct from w.
func (c *FilmClient) Add(ctx context.Context, w *Film) error {
	return c.schemaClient.Add(ctx, w.s)
}

// Update modifies the underlying schema struct from w (must have UID set).
func (c *FilmClient) Update(ctx context.Context, w *Film) error {
	return c.schemaClient.Update(ctx, w.s)
}

// Upsert inserts or updates the underlying schema struct from w, matching
// against predicates. If no predicates are provided, the first field tagged
// dgraph:"upsert" wins.
func (c *FilmClient) Upsert(ctx context.Context, w *Film, predicates ...string) error {
	return c.schemaClient.Upsert(ctx, w.s, predicates...)
}

// Delete removes the Film with the given UID.
func (c *FilmClient) Delete(ctx context.Context, uid string) error {
	return c.schemaClient.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Film.
func (c *FilmClient) Query(ctx context.Context) *FilmQuery {
	return &FilmQuery{schemaQuery: c.schemaClient.Query(ctx)}
}
