// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"time"
)

// FilmOption configures a *Film. Applied at construction time via
// NewFilm or WrapFilm, or in bulk later via ApplyFilmOptions.
type FilmOption func(*Film)

// ApplyFilmOptions applies a sequence of options to e in order.
func ApplyFilmOptions(e *Film, opts ...FilmOption) {
	for _, opt := range opts {
		opt(e)
	}
}

// WithFilmName sets the name field on a *Film.
func WithFilmName(v string) FilmOption {
	return func(e *Film) { e.SetName(v) }
}

// WithFilmInitialReleaseDate sets the initialReleaseDate field on a *Film.
func WithFilmInitialReleaseDate(v time.Time) FilmOption {
	return func(e *Film) { e.SetInitialReleaseDate(v) }
}

// WithFilmTagline sets the tagline field on a *Film.
func WithFilmTagline(v string) FilmOption {
	return func(e *Film) { e.SetTagline(v) }
}
