// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "github.com/mlwelles/modusGraphMoviesProject/schema"

// FilmQuery is the wrapper-side query builder. Composes over
// schema.FilmQuery; terminal methods wrap results before returning.
type FilmQuery struct {
	schemaQuery *schema.FilmQuery
}

// Nodes executes the query and returns wrapped Film results.
func (q *FilmQuery) Nodes() ([]*Film, error) {
	var recs []schema.Film
	if err := q.schemaQuery.Nodes(&recs); err != nil {
		return nil, err
	}
	out := make([]*Film, len(recs))
	for i := range recs {
		out[i] = WrapFilm(&recs[i])
	}
	return out, nil
}

// First returns the first matching wrapper, or nil if no rows.
func (q *FilmQuery) First() (*Film, error) {
	s, err := q.schemaQuery.First()
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, nil
	}
	return WrapFilm(s), nil
}
