// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "github.com/mlwelles/modusGraphMoviesProject/schema"

// GenreQuery is the wrapper-side query builder. Composes over
// schema.GenreQuery; terminal methods wrap results before returning.
type GenreQuery struct {
	schemaQuery *schema.GenreQuery
}

// Nodes executes the query and returns wrapped Genre results.
func (q *GenreQuery) Nodes() ([]*Genre, error) {
	var recs []schema.Genre
	if err := q.schemaQuery.Nodes(&recs); err != nil {
		return nil, err
	}
	out := make([]*Genre, len(recs))
	for i := range recs {
		out[i] = WrapGenre(&recs[i])
	}
	return out, nil
}

// First returns the first matching wrapper, or nil if no rows.
func (q *GenreQuery) First() (*Genre, error) {
	s, err := q.schemaQuery.First()
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, nil
	}
	return WrapGenre(s), nil
}
