// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Genre wraps a schema.Genre and exposes its data through methods.
// It embeds typed.Wrapper, which supplies Unwrap, JSON marshaling, and
// validation; the backing schema struct is reachable only via Unwrap().
type Genre struct {
	typed.Wrapper[schema.Genre]
}

// NewGenre constructs a Genre with a fresh, empty schema struct, then
// applies the given options.
func NewGenre(opts ...typed.Option[Genre]) *Genre {
	e := &Genre{Wrapper: typed.WrapValue(&schema.Genre{})}
	typed.Apply(e, opts...)
	return e
}

// WrapGenre constructs a Genre backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive
// copy, so setters mutate the caller's struct.
func WrapGenre(s *schema.Genre, opts ...typed.Option[Genre]) *Genre {
	e := &Genre{Wrapper: typed.WrapValue(s)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Genre) UID() string { return e.Unwrap().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Genre) SetUID(v string) { e.Unwrap().UID = v }

// DType returns the entity's dgraph type list.
func (e *Genre) DType() []string { return e.Unwrap().DType }

// SetDType sets the entity's dgraph type list.
func (e *Genre) SetDType(v []string) { e.Unwrap().DType = v }
