// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"iter"

	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// GenreQuery is the wrapper-side fluent query builder for Genre. Builder
// methods return *GenreQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type GenreQuery struct {
	typed *typed.Query[schema.Genre]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *GenreQuery) Filter(filter string, params ...any) *GenreQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *GenreQuery) OrderAsc(clause string) *GenreQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *GenreQuery) OrderDesc(clause string) *GenreQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *GenreQuery) Limit(n int) *GenreQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *GenreQuery) Offset(n int) *GenreQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *GenreQuery) After(uid string) *GenreQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *GenreQuery) Cascade(predicates ...string) *GenreQuery {
	q.typed.Cascade(predicates...)
	return q
}

// Nodes executes the query and returns wrapped Genre results.
func (q *GenreQuery) Nodes() ([]*Genre, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Genre, len(recs))
	for i := range recs {
		out[i] = WrapGenre(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// wrapped Genre, or nil if no rows matched.
func (q *GenreQuery) First() (*Genre, error) {
	s, err := q.typed.First()
	if err != nil || s == nil {
		return nil, err
	}
	return WrapGenre(s), nil
}

// IterNodes streams the query's results as wrapped Genre values, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *GenreQuery) IterNodes() iter.Seq2[*Genre, error] {
	return func(yield func(*Genre, error) bool) {
		for s, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(WrapGenre(s), nil) {
				return
			}
		}
	}
}
