// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// GenreClient provides CRUD/query operations over Genre wrapper values.
// It composes over a typed.Client bound to the schema struct: reads wrap the
// schema result, writes forward the wrapper's backing struct.
type GenreClient struct {
	typed *typed.Client[schema.Genre]
}

// NewGenreClient binds a GenreClient to conn.
func NewGenreClient(conn modusgraph.Client) *GenreClient {
	return &GenreClient{typed: typed.NewClient[schema.Genre](conn)}
}

// Get loads the Genre with the given UID and returns it wrapped.
func (c *GenreClient) Get(ctx context.Context, uid string) (*Genre, error) {
	s, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapGenre(s), nil
}

// Add inserts the schema struct backing w.
func (c *GenreClient) Add(ctx context.Context, w *Genre) error {
	return c.typed.Add(ctx, w.Unwrap())
}

// Update modifies the schema struct backing w (must have UID set).
func (c *GenreClient) Update(ctx context.Context, w *Genre) error {
	return c.typed.Update(ctx, w.Unwrap())
}

// Upsert inserts or updates the schema struct backing w, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *GenreClient) Upsert(ctx context.Context, w *Genre, predicates ...string) error {
	return c.typed.Upsert(ctx, w.Unwrap(), predicates...)
}

// Delete removes the Genre with the given UID.
func (c *GenreClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Genre.
func (c *GenreClient) Query(ctx context.Context) *GenreQuery {
	return &GenreQuery{typed: c.typed.Query(ctx)}
}
