// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"
)

// WithGenreName sets the name field on a *Genre.
func WithGenreName(v string) typed.Option[Genre] {
	return func(e *Genre) { e.SetName(v) }
}
