// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// GenreClient wraps a schema.GenreClient and exposes the same
// operations over wrapper types. Reads allocate a wrapper around the schema
// result; writes deref the wrapper's backing schema struct (w.s) and forward.
type GenreClient struct {
	schemaClient *schema.GenreClient
}

// NewGenreClient binds a wrapper-side GenreClient to conn. Internally
// constructs a fresh schema.GenreClient on the same conn.
func NewGenreClient(conn modusgraph.Client) *GenreClient {
	return &GenreClient{schemaClient: schema.NewGenreClient(conn)}
}

// Get loads the Genre with the given UID and returns it wrapped.
func (c *GenreClient) Get(ctx context.Context, uid string) (*Genre, error) {
	s, err := c.schemaClient.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapGenre(s), nil
}

// Add inserts the underlying schema struct from w.
func (c *GenreClient) Add(ctx context.Context, w *Genre) error {
	return c.schemaClient.Add(ctx, w.s)
}

// Update modifies the underlying schema struct from w (must have UID set).
func (c *GenreClient) Update(ctx context.Context, w *Genre) error {
	return c.schemaClient.Update(ctx, w.s)
}

// Upsert inserts or updates the underlying schema struct from w, matching
// against predicates. If no predicates are provided, the first field tagged
// dgraph:"upsert" wins.
func (c *GenreClient) Upsert(ctx context.Context, w *Genre, predicates ...string) error {
	return c.schemaClient.Upsert(ctx, w.s, predicates...)
}

// Delete removes the Genre with the given UID.
func (c *GenreClient) Delete(ctx context.Context, uid string) error {
	return c.schemaClient.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Genre.
func (c *GenreClient) Query(ctx context.Context) *GenreQuery {
	return &GenreQuery{schemaQuery: c.schemaClient.Query(ctx)}
}
