// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"slices"
)

// Name returns the name field.
func (e *Location) Name() string { return e.s.Name }

// SetName sets the name field.
func (e *Location) SetName(v string) { e.s.Name = v }

// Email returns the email field.
func (e *Location) Email() string { return e.s.Email }

// SetEmail sets the email field.
func (e *Location) SetEmail(v string) { e.s.Email = v }

// Loc returns the scalar slice.
func (e *Location) Loc() []float64 { return e.s.Loc }

// SetLoc sets the scalar slice.
func (e *Location) SetLoc(v []float64) { e.s.Loc = v }

// AppendLoc appends values to the scalar slice.
func (e *Location) AppendLoc(v ...float64) {
	e.s.Loc = append(e.s.Loc, v...)
}

// RemoveLocFunc removes all elements for which fn returns true.
func (e *Location) RemoveLocFunc(fn func(float64) bool) {
	e.s.Loc = slices.DeleteFunc(e.s.Loc, fn)
}
