// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"
)

// WithLocationName sets the name field on a *Location.
func WithLocationName(v string) typed.Option[Location] {
	return func(e *Location) { e.SetName(v) }
}

// WithLocationEmail sets the email field on a *Location.
func WithLocationEmail(v string) typed.Option[Location] {
	return func(e *Location) { e.SetEmail(v) }
}
