// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "github.com/mlwelles/modusGraphMoviesProject/schema"

// LocationQuery is the wrapper-side query builder. Composes over
// schema.LocationQuery; terminal methods wrap results before returning.
type LocationQuery struct {
	schemaQuery *schema.LocationQuery
}

// Nodes executes the query and returns wrapped Location results.
func (q *LocationQuery) Nodes() ([]*Location, error) {
	var recs []schema.Location
	if err := q.schemaQuery.Nodes(&recs); err != nil {
		return nil, err
	}
	out := make([]*Location, len(recs))
	for i := range recs {
		out[i] = WrapLocation(&recs[i])
	}
	return out, nil
}

// First returns the first matching wrapper, or nil if no rows.
func (q *LocationQuery) First() (*Location, error) {
	s, err := q.schemaQuery.First()
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, nil
	}
	return WrapLocation(s), nil
}
