// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Location wraps a schema.Location and exposes its data through methods.
// It embeds typed.Wrapper, which supplies Unwrap, JSON marshaling, and
// validation; the backing schema struct is reachable only via Unwrap().
type Location struct {
	typed.Wrapper[schema.Location]
}

// NewLocation constructs a Location with a fresh, empty schema struct, then
// applies the given options.
func NewLocation(opts ...typed.Option[Location]) *Location {
	e := &Location{Wrapper: typed.WrapValue(&schema.Location{})}
	typed.Apply(e, opts...)
	return e
}

// WrapLocation constructs a Location backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive
// copy, so setters mutate the caller's struct.
func WrapLocation(s *schema.Location, opts ...typed.Option[Location]) *Location {
	e := &Location{Wrapper: typed.WrapValue(s)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Location) UID() string { return e.Unwrap().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Location) SetUID(v string) { e.Unwrap().UID = v }

// DType returns the entity's dgraph type list.
func (e *Location) DType() []string { return e.Unwrap().DType }

// SetDType sets the entity's dgraph type list.
func (e *Location) SetDType(v []string) { e.Unwrap().DType = v }
