// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"
	"encoding/json"

	"github.com/go-playground/validator/v10"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Location wraps a schema.Location and exposes its data through
// methods. The backing schema struct is held in s; the only way to obtain
// it is via Unwrap(). All mutation goes through generated setters that
// write to s, so the wrapper has no state of its own.
type Location struct {
	s *schema.Location
}

// NewLocation constructs a Location with a fresh, empty schema struct inside,
// then applies the given options.
func NewLocation(opts ...LocationOption) *Location {
	e := &Location{s: &schema.Location{}}
	for _, opt := range opts {
		opt(e)
	}
	return e
}

// WrapLocation constructs a Location backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive copy.
// Mutations through Location's setters write to s.
func WrapLocation(s *schema.Location, opts ...LocationOption) *Location {
	e := &Location{s: s}
	for _, opt := range opts {
		opt(e)
	}
	return e
}

// Unwrap returns the backing schema struct. modusgraph.Client uses this
// (via reflection) to substitute the schema struct when a wrapper is
// passed across the boundary.
func (e *Location) Unwrap() *schema.Location { return e.s }

// UID returns the entity's UID bookkeeping field.
func (e *Location) UID() string { return e.s.UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Location) SetUID(v string) { e.s.UID = v }

// DType returns the entity's dgraph type list.
func (e *Location) DType() []string { return e.s.DType }

// SetDType sets the entity's dgraph type list.
func (e *Location) SetDType(v []string) { e.s.DType = v }

// Validate runs v against the backing schema struct. The validator's tag
// processing sees the schema struct's public fields directly.
func (e *Location) Validate(ctx context.Context, v *validator.Validate) error {
	return v.StructCtx(ctx, e.s)
}

// MarshalJSON delegates to the schema struct, whose public fields and
// json tags produce the correct serialization.
func (e *Location) MarshalJSON() ([]byte, error) {
	return json.Marshal(e.s)
}

// UnmarshalJSON lazily initializes the backing schema struct if needed,
// then delegates. Safe to call on a zero-value *Location.
func (e *Location) UnmarshalJSON(data []byte) error {
	if e.s == nil {
		e.s = &schema.Location{}
	}
	return json.Unmarshal(data, e.s)
}
