// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// LocationQuery is the wrapper-side fluent query builder for Location. Builder
// methods return *LocationQuery for chaining; terminal methods (Nodes, First)
// execute the query and wrap results.
type LocationQuery struct {
	typed *typed.Query[schema.Location]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *LocationQuery) Filter(filter string, params ...any) *LocationQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *LocationQuery) OrderAsc(clause string) *LocationQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *LocationQuery) OrderDesc(clause string) *LocationQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *LocationQuery) Limit(n int) *LocationQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *LocationQuery) Offset(n int) *LocationQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *LocationQuery) After(uid string) *LocationQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *LocationQuery) Cascade(predicates ...string) *LocationQuery {
	q.typed.Cascade(predicates...)
	return q
}

// Nodes executes the query and returns wrapped Location results.
func (q *LocationQuery) Nodes() ([]*Location, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Location, len(recs))
	for i := range recs {
		out[i] = WrapLocation(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// wrapped Location, or nil if no rows matched.
func (q *LocationQuery) First() (*Location, error) {
	s, err := q.typed.First()
	if err != nil || s == nil {
		return nil, err
	}
	return WrapLocation(s), nil
}
