// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// LocationClient wraps a schema.LocationClient and exposes the same
// operations over wrapper types. Reads allocate a wrapper around the schema
// result; writes deref the wrapper's backing schema struct (w.s) and forward.
type LocationClient struct {
	schemaClient *schema.LocationClient
}

// NewLocationClient binds a wrapper-side LocationClient to conn. Internally
// constructs a fresh schema.LocationClient on the same conn.
func NewLocationClient(conn modusgraph.Client) *LocationClient {
	return &LocationClient{schemaClient: schema.NewLocationClient(conn)}
}

// Get loads the Location with the given UID and returns it wrapped.
func (c *LocationClient) Get(ctx context.Context, uid string) (*Location, error) {
	s, err := c.schemaClient.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapLocation(s), nil
}

// Add inserts the underlying schema struct from w.
func (c *LocationClient) Add(ctx context.Context, w *Location) error {
	return c.schemaClient.Add(ctx, w.s)
}

// Update modifies the underlying schema struct from w (must have UID set).
func (c *LocationClient) Update(ctx context.Context, w *Location) error {
	return c.schemaClient.Update(ctx, w.s)
}

// Upsert inserts or updates the underlying schema struct from w, matching
// against predicates. If no predicates are provided, the first field tagged
// dgraph:"upsert" wins.
func (c *LocationClient) Upsert(ctx context.Context, w *Location, predicates ...string) error {
	return c.schemaClient.Upsert(ctx, w.s, predicates...)
}

// Delete removes the Location with the given UID.
func (c *LocationClient) Delete(ctx context.Context, uid string) error {
	return c.schemaClient.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Location.
func (c *LocationClient) Query(ctx context.Context) *LocationQuery {
	return &LocationQuery{schemaQuery: c.schemaClient.Query(ctx)}
}
