// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Performance wraps a schema.Performance and exposes its data through methods.
// It embeds typed.Wrapper, which supplies Unwrap, JSON marshaling, and
// validation; the backing schema struct is reachable only via Unwrap().
type Performance struct {
	typed.Wrapper[schema.Performance]
}

// NewPerformance constructs a Performance with a fresh, empty schema struct, then
// applies the given options.
func NewPerformance(opts ...typed.Option[Performance]) *Performance {
	e := &Performance{Wrapper: typed.WrapValue(&schema.Performance{})}
	typed.Apply(e, opts...)
	return e
}

// WrapPerformance constructs a Performance backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive
// copy, so setters mutate the caller's struct.
func WrapPerformance(s *schema.Performance, opts ...typed.Option[Performance]) *Performance {
	e := &Performance{Wrapper: typed.WrapValue(s)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Performance) UID() string { return e.Unwrap().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Performance) SetUID(v string) { e.Unwrap().UID = v }

// DType returns the entity's dgraph type list.
func (e *Performance) DType() []string { return e.Unwrap().DType }

// SetDType sets the entity's dgraph type list.
func (e *Performance) SetDType(v []string) { e.Unwrap().DType = v }
