// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// PerformanceQuery is the wrapper-side fluent query builder for Performance. Builder
// methods return *PerformanceQuery for chaining; terminal methods (Nodes, First)
// execute the query and wrap results.
type PerformanceQuery struct {
	typed *typed.Query[schema.Performance]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *PerformanceQuery) Filter(filter string, params ...any) *PerformanceQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *PerformanceQuery) OrderAsc(clause string) *PerformanceQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *PerformanceQuery) OrderDesc(clause string) *PerformanceQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *PerformanceQuery) Limit(n int) *PerformanceQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *PerformanceQuery) Offset(n int) *PerformanceQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *PerformanceQuery) After(uid string) *PerformanceQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *PerformanceQuery) Cascade(predicates ...string) *PerformanceQuery {
	q.typed.Cascade(predicates...)
	return q
}

// Nodes executes the query and returns wrapped Performance results.
func (q *PerformanceQuery) Nodes() ([]*Performance, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Performance, len(recs))
	for i := range recs {
		out[i] = WrapPerformance(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// wrapped Performance, or nil if no rows matched.
func (q *PerformanceQuery) First() (*Performance, error) {
	s, err := q.typed.First()
	if err != nil || s == nil {
		return nil, err
	}
	return WrapPerformance(s), nil
}
