// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"
)

// WithPerformanceCharacterNote sets the characterNote field on a *Performance.
func WithPerformanceCharacterNote(v string) typed.Option[Performance] {
	return func(e *Performance) { e.SetCharacterNote(v) }
}
