// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "github.com/mlwelles/modusGraphMoviesProject/schema"

// PerformanceQuery is the wrapper-side query builder. Composes over
// schema.PerformanceQuery; terminal methods wrap results before returning.
type PerformanceQuery struct {
	schemaQuery *schema.PerformanceQuery
}

// Nodes executes the query and returns wrapped Performance results.
func (q *PerformanceQuery) Nodes() ([]*Performance, error) {
	var recs []schema.Performance
	if err := q.schemaQuery.Nodes(&recs); err != nil {
		return nil, err
	}
	out := make([]*Performance, len(recs))
	for i := range recs {
		out[i] = WrapPerformance(&recs[i])
	}
	return out, nil
}

// First returns the first matching wrapper, or nil if no rows.
func (q *PerformanceQuery) First() (*Performance, error) {
	s, err := q.schemaQuery.First()
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, nil
	}
	return WrapPerformance(s), nil
}
