// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// PerformanceOption configures a *Performance. Applied at construction time via
// NewPerformance or WrapPerformance, or in bulk later via ApplyPerformanceOptions.
type PerformanceOption func(*Performance)

// ApplyPerformanceOptions applies a sequence of options to e in order.
func ApplyPerformanceOptions(e *Performance, opts ...PerformanceOption) {
	for _, opt := range opts {
		opt(e)
	}
}

// WithPerformanceCharacterNote sets the characterNote field on a *Performance.
func WithPerformanceCharacterNote(v string) PerformanceOption {
	return func(e *Performance) { e.SetCharacterNote(v) }
}
