// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// CharacterNote returns the characterNote field.
func (e *Performance) CharacterNote() string { return e.s.CharacterNote }

// SetCharacterNote sets the characterNote field.
func (e *Performance) SetCharacterNote(v string) { e.s.CharacterNote = v }
