// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"iter"

	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// RatingQuery is the wrapper-side fluent query builder for Rating. Builder
// methods return *RatingQuery for chaining; terminal methods (Nodes, First,
// IterNodes) execute the query and wrap results.
type RatingQuery struct {
	typed *typed.Query[schema.Rating]
}

// Filter adds a dgraph @filter expression. params bind to placeholders.
func (q *RatingQuery) Filter(filter string, params ...any) *RatingQuery {
	q.typed.Filter(filter, params...)
	return q
}

// OrderAsc orders results ascending by clause.
func (q *RatingQuery) OrderAsc(clause string) *RatingQuery {
	q.typed.OrderAsc(clause)
	return q
}

// OrderDesc orders results descending by clause.
func (q *RatingQuery) OrderDesc(clause string) *RatingQuery {
	q.typed.OrderDesc(clause)
	return q
}

// Limit caps the number of results.
func (q *RatingQuery) Limit(n int) *RatingQuery {
	q.typed.Limit(n)
	return q
}

// Offset skips the first n results.
func (q *RatingQuery) Offset(n int) *RatingQuery {
	q.typed.Offset(n)
	return q
}

// After returns results with UID greater than uid (cursor pagination).
func (q *RatingQuery) After(uid string) *RatingQuery {
	q.typed.After(uid)
	return q
}

// Cascade drops nodes missing any of the given predicates.
func (q *RatingQuery) Cascade(predicates ...string) *RatingQuery {
	q.typed.Cascade(predicates...)
	return q
}

// WhereFilms keeps only Rating records that have a ~rating
// edge whose target node matches the dgraph @filter expression. params bind to
// $N placeholders. Multiple Where* calls are combined with AND.
func (q *RatingQuery) WhereFilms(filter string, params ...any) *RatingQuery {
	q.typed.WhereEdge("~rating", filter, params...)
	return q
}

// Nodes executes the query and returns wrapped Rating results.
func (q *RatingQuery) Nodes() ([]*Rating, error) {
	recs, err := q.typed.Nodes()
	if err != nil {
		return nil, err
	}
	out := make([]*Rating, len(recs))
	for i := range recs {
		out[i] = WrapRating(&recs[i])
	}
	return out, nil
}

// First executes the query with an implicit Limit(1) and returns the first
// wrapped Rating, or nil if no rows matched.
func (q *RatingQuery) First() (*Rating, error) {
	s, err := q.typed.First()
	if err != nil || s == nil {
		return nil, err
	}
	return WrapRating(s), nil
}

// IterNodes streams the query's results as wrapped Rating values, paging
// transparently. It is a terminal operation; see typed.Query.IterNodes.
func (q *RatingQuery) IterNodes() iter.Seq2[*Rating, error] {
	return func(yield func(*Rating, error) bool) {
		for s, err := range q.typed.IterNodes() {
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(WrapRating(s), nil) {
				return
			}
		}
	}
}
