// Code generated by modusGraphGen. DO NOT EDIT.

package movies

// RatingOption configures a *Rating. Applied at construction time via
// NewRating or WrapRating, or in bulk later via ApplyRatingOptions.
type RatingOption func(*Rating)

// ApplyRatingOptions applies a sequence of options to e in order.
func ApplyRatingOptions(e *Rating, opts ...RatingOption) {
	for _, opt := range opts {
		opt(e)
	}
}

// WithRatingName sets the name field on a *Rating.
func WithRatingName(v string) RatingOption {
	return func(e *Rating) { e.SetName(v) }
}
