// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// RatingClient wraps a schema.RatingClient and exposes the same
// operations over wrapper types. Reads allocate a wrapper around the schema
// result; writes deref the wrapper's backing schema struct (w.s) and forward.
type RatingClient struct {
	schemaClient *schema.RatingClient
}

// NewRatingClient binds a wrapper-side RatingClient to conn. Internally
// constructs a fresh schema.RatingClient on the same conn.
func NewRatingClient(conn modusgraph.Client) *RatingClient {
	return &RatingClient{schemaClient: schema.NewRatingClient(conn)}
}

// Get loads the Rating with the given UID and returns it wrapped.
func (c *RatingClient) Get(ctx context.Context, uid string) (*Rating, error) {
	s, err := c.schemaClient.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapRating(s), nil
}

// Add inserts the underlying schema struct from w.
func (c *RatingClient) Add(ctx context.Context, w *Rating) error {
	return c.schemaClient.Add(ctx, w.s)
}

// Update modifies the underlying schema struct from w (must have UID set).
func (c *RatingClient) Update(ctx context.Context, w *Rating) error {
	return c.schemaClient.Update(ctx, w.s)
}

// Upsert inserts or updates the underlying schema struct from w, matching
// against predicates. If no predicates are provided, the first field tagged
// dgraph:"upsert" wins.
func (c *RatingClient) Upsert(ctx context.Context, w *Rating, predicates ...string) error {
	return c.schemaClient.Upsert(ctx, w.s, predicates...)
}

// Delete removes the Rating with the given UID.
func (c *RatingClient) Delete(ctx context.Context, uid string) error {
	return c.schemaClient.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Rating.
func (c *RatingClient) Query(ctx context.Context) *RatingQuery {
	return &RatingQuery{schemaQuery: c.schemaClient.Query(ctx)}
}
