// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Rating wraps a schema.Rating and exposes its data through methods.
// It embeds typed.Wrapper, which supplies Unwrap, JSON marshaling, and
// validation; the backing schema struct is reachable only via Unwrap().
type Rating struct {
	typed.Wrapper[schema.Rating]
}

// NewRating constructs a Rating with a fresh, empty schema struct, then
// applies the given options.
func NewRating(opts ...typed.Option[Rating]) *Rating {
	e := &Rating{Wrapper: typed.WrapValue(&schema.Rating{})}
	typed.Apply(e, opts...)
	return e
}

// WrapRating constructs a Rating backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive
// copy, so setters mutate the caller's struct.
func WrapRating(s *schema.Rating, opts ...typed.Option[Rating]) *Rating {
	e := &Rating{Wrapper: typed.WrapValue(s)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Rating) UID() string { return e.Unwrap().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Rating) SetUID(v string) { e.Unwrap().UID = v }

// DType returns the entity's dgraph type list.
func (e *Rating) DType() []string { return e.Unwrap().DType }

// SetDType sets the entity's dgraph type list.
func (e *Rating) SetDType(v []string) { e.Unwrap().DType = v }
