// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"

// RatingQuery is the wrapper-side query builder. Composes over
// schema.RatingQuery; terminal methods wrap results before returning.
type RatingQuery struct {
	schemaQuery *schema.RatingQuery
}

// Nodes executes the query and returns wrapped Rating results.
func (q *RatingQuery) Nodes() ([]*Rating, error) {
	var recs []schema.Rating
	if err := q.schemaQuery.Nodes(&recs); err != nil {
		return nil, err
	}
	out := make([]*Rating, len(recs))
	for i := range recs {
		out[i] = WrapRating(&recs[i])
	}
	return out, nil
}

// First returns the first matching wrapper, or nil if no rows.
func (q *RatingQuery) First() (*Rating, error) {
	s, err := q.schemaQuery.First()
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, nil
	}
	return WrapRating(s), nil
}
