// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"
)

// WithRatingName sets the name field on a *Rating.
func WithRatingName(v string) typed.Option[Rating] {
	return func(e *Rating) { e.SetName(v) }
}
