// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// RatingClient provides CRUD/query operations over Rating wrapper values.
// It composes over a typed.Client bound to the schema struct: reads wrap the
// schema result, writes forward the wrapper's backing struct.
type RatingClient struct {
	typed *typed.Client[schema.Rating]
}

// NewRatingClient binds a RatingClient to conn.
func NewRatingClient(conn modusgraph.Client) *RatingClient {
	return &RatingClient{typed: typed.NewClient[schema.Rating](conn)}
}

// Get loads the Rating with the given UID and returns it wrapped.
func (c *RatingClient) Get(ctx context.Context, uid string) (*Rating, error) {
	s, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapRating(s), nil
}

// Add inserts the schema struct backing w.
func (c *RatingClient) Add(ctx context.Context, w *Rating) error {
	return c.typed.Add(ctx, w.Unwrap())
}

// Update modifies the schema struct backing w (must have UID set).
func (c *RatingClient) Update(ctx context.Context, w *Rating) error {
	return c.typed.Update(ctx, w.Unwrap())
}

// Upsert inserts or updates the schema struct backing w, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *RatingClient) Upsert(ctx context.Context, w *Rating, predicates ...string) error {
	return c.typed.Upsert(ctx, w.Unwrap(), predicates...)
}

// Delete removes the Rating with the given UID.
func (c *RatingClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Rating.
func (c *RatingClient) Query(ctx context.Context) *RatingQuery {
	return &RatingQuery{typed: c.typed.Query(ctx)}
}
