// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	dg "github.com/dolan-in/dgman/v2"
	"time"
)

// WithStudioName sets the name field on a *Studio.
func WithStudioName(v string) typed.Option[Studio] {
	return func(e *Studio) { e.SetName(v) }
}

// WithStudioYearFounded sets the yearFounded field on a *Studio.
func WithStudioYearFounded(v int) typed.Option[Studio] {
	return func(e *Studio) { e.SetYearFounded(v) }
}

// WithStudioRevenue sets the revenue field on a *Studio.
func WithStudioRevenue(v float64) typed.Option[Studio] {
	return func(e *Studio) { e.SetRevenue(v) }
}

// WithStudioActive sets the active field on a *Studio.
func WithStudioActive(v bool) typed.Option[Studio] {
	return func(e *Studio) { e.SetActive(v) }
}

// WithStudioCreatedAt sets the createdAt field on a *Studio.
func WithStudioCreatedAt(v time.Time) typed.Option[Studio] {
	return func(e *Studio) { e.SetCreatedAt(v) }
}

// WithStudioEmbedding sets the embedding field on a *Studio.
func WithStudioEmbedding(v *dg.VectorFloat32) typed.Option[Studio] {
	return func(e *Studio) { e.SetEmbedding(v) }
}
