// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"

	"github.com/mlwelles/modusGraphMoviesProject/schema"
)

// StudioClient wraps a schema.StudioClient and exposes the same
// operations over wrapper types. Reads allocate a wrapper around the schema
// result; writes deref the wrapper's backing schema struct (w.s) and forward.
type StudioClient struct {
	schemaClient *schema.StudioClient
}

// NewStudioClient binds a wrapper-side StudioClient to conn. Internally
// constructs a fresh schema.StudioClient on the same conn.
func NewStudioClient(conn modusgraph.Client) *StudioClient {
	return &StudioClient{schemaClient: schema.NewStudioClient(conn)}
}

// Get loads the Studio with the given UID and returns it wrapped.
func (c *StudioClient) Get(ctx context.Context, uid string) (*Studio, error) {
	s, err := c.schemaClient.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapStudio(s), nil
}

// Add inserts the underlying schema struct from w.
func (c *StudioClient) Add(ctx context.Context, w *Studio) error {
	return c.schemaClient.Add(ctx, w.s)
}

// Update modifies the underlying schema struct from w (must have UID set).
func (c *StudioClient) Update(ctx context.Context, w *Studio) error {
	return c.schemaClient.Update(ctx, w.s)
}

// Upsert inserts or updates the underlying schema struct from w, matching
// against predicates. If no predicates are provided, the first field tagged
// dgraph:"upsert" wins.
func (c *StudioClient) Upsert(ctx context.Context, w *Studio, predicates ...string) error {
	return c.schemaClient.Upsert(ctx, w.s, predicates...)
}

// Delete removes the Studio with the given UID.
func (c *StudioClient) Delete(ctx context.Context, uid string) error {
	return c.schemaClient.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Studio.
func (c *StudioClient) Query(ctx context.Context) *StudioQuery {
	return &StudioQuery{schemaQuery: c.schemaClient.Query(ctx)}
}
