// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Studio wraps a schema.Studio and exposes its data through methods.
// It embeds typed.Wrapper, which supplies Unwrap, JSON marshaling, and
// validation; the backing schema struct is reachable only via Unwrap().
type Studio struct {
	typed.Wrapper[schema.Studio]
}

// NewStudio constructs a Studio with a fresh, empty schema struct, then
// applies the given options.
func NewStudio(opts ...typed.Option[Studio]) *Studio {
	e := &Studio{Wrapper: typed.WrapValue(&schema.Studio{})}
	typed.Apply(e, opts...)
	return e
}

// WrapStudio constructs a Studio backed by the given schema struct, then
// applies the given options. The wrapper holds s directly — no defensive
// copy, so setters mutate the caller's struct.
func WrapStudio(s *schema.Studio, opts ...typed.Option[Studio]) *Studio {
	e := &Studio{Wrapper: typed.WrapValue(s)}
	typed.Apply(e, opts...)
	return e
}

// UID returns the entity's UID bookkeeping field.
func (e *Studio) UID() string { return e.Unwrap().UID }

// SetUID sets the entity's UID bookkeeping field.
func (e *Studio) SetUID(v string) { e.Unwrap().UID = v }

// DType returns the entity's dgraph type list.
func (e *Studio) DType() []string { return e.Unwrap().DType }

// SetDType sets the entity's dgraph type list.
func (e *Studio) SetDType(v []string) { e.Unwrap().DType = v }
