// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import "github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"

// StudioQuery is the wrapper-side query builder. Composes over
// schema.StudioQuery; terminal methods wrap results before returning.
type StudioQuery struct {
	schemaQuery *schema.StudioQuery
}

// Nodes executes the query and returns wrapped Studio results.
func (q *StudioQuery) Nodes() ([]*Studio, error) {
	var recs []schema.Studio
	if err := q.schemaQuery.Nodes(&recs); err != nil {
		return nil, err
	}
	out := make([]*Studio, len(recs))
	for i := range recs {
		out[i] = WrapStudio(&recs[i])
	}
	return out, nil
}

// First returns the first matching wrapper, or nil if no rows.
func (q *StudioQuery) First() (*Studio, error) {
	s, err := q.schemaQuery.First()
	if err != nil {
		return nil, err
	}
	if s == nil {
		return nil, nil
	}
	return WrapStudio(s), nil
}
