// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"iter"
	"slices"
	"time"

	"github.com/matthewmcneely/modusgraph/typed"

	dg "github.com/dolan-in/dgman/v2"
	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// Name returns the name field.
func (e *Studio) Name() string { return e.Unwrap().Name }

// SetName sets the name field.
func (e *Studio) SetName(v string) { e.Unwrap().Name = v }

// YearFounded returns the yearFounded field.
func (e *Studio) YearFounded() int { return e.Unwrap().YearFounded }

// SetYearFounded sets the yearFounded field.
func (e *Studio) SetYearFounded(v int) { e.Unwrap().YearFounded = v }

// Revenue returns the revenue field.
func (e *Studio) Revenue() float64 { return e.Unwrap().Revenue }

// SetRevenue sets the revenue field.
func (e *Studio) SetRevenue(v float64) { e.Unwrap().Revenue = v }

// Active returns the active field.
func (e *Studio) Active() bool { return e.Unwrap().Active }

// SetActive sets the active field.
func (e *Studio) SetActive(v bool) { e.Unwrap().Active = v }

// CreatedAt returns the createdAt field.
func (e *Studio) CreatedAt() time.Time { return e.Unwrap().CreatedAt }

// SetCreatedAt sets the createdAt field.
func (e *Studio) SetCreatedAt(v time.Time) { e.Unwrap().CreatedAt = v }

// Embedding returns the embedding field.
func (e *Studio) Embedding() *dg.VectorFloat32 { return e.Unwrap().Embedding }

// SetEmbedding sets the embedding field.
func (e *Studio) SetEmbedding(v *dg.VectorFloat32) { e.Unwrap().Embedding = v }

// Founder returns the wrapped Director, or nil if not set.
// Shared state: mutations through the returned wrapper write through to e.
func (e *Studio) Founder() *Director {
	if e.Unwrap().Founder == nil {
		return nil
	}
	return &Director{Wrapper: typed.WrapValue(e.Unwrap().Founder)}
}

// SetFounder sets or clears the Director edge.
func (e *Studio) SetFounder(v *Director) {
	if v == nil {
		e.Unwrap().Founder = nil
		return
	}
	e.Unwrap().Founder = v.Unwrap()
}

// Headquarters returns a wrapper over the value-typed schema field. The wrapper
// shares state with e — mutations are visible to e immediately.
func (e *Studio) Headquarters() *Country {
	return &Country{Wrapper: typed.WrapValue(&e.Unwrap().Headquarters)}
}

// SetHeadquarters copies the value from v into the schema field. Note: this is
// a value copy, so v and e.Headquarters() will not share state after this call.
func (e *Studio) SetHeadquarters(v *Country) {
	if v != nil {
		e.Unwrap().Headquarters = *v.Unwrap()
	}
}

// CurrentHead returns the wrapped first element of the singular-via-list edge,
// or nil if the list is empty.
func (e *Studio) CurrentHead() *Director {
	if len(e.Unwrap().CurrentHead) == 0 || e.Unwrap().CurrentHead[0] == nil {
		return nil
	}
	return &Director{Wrapper: typed.WrapValue(e.Unwrap().CurrentHead[0])}
}

// SetCurrentHead replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetCurrentHead(v *Director) {
	if v == nil {
		e.Unwrap().CurrentHead = nil
		return
	}
	e.Unwrap().CurrentHead = []*schema.Director{v.Unwrap()}
}

// Ceo returns the wrapped first element of the singular-via-list edge,
// or nil if the list is empty.
func (e *Studio) Ceo() *Director {
	if len(e.Unwrap().Ceo) == 0 || e.Unwrap().Ceo[0] == nil {
		return nil
	}
	return &Director{Wrapper: typed.WrapValue(e.Unwrap().Ceo[0])}
}

// SetCeo replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetCeo(v *Director) {
	if v == nil {
		e.Unwrap().Ceo = nil
		return
	}
	e.Unwrap().Ceo = []*schema.Director{v.Unwrap()}
}

// HomeBase returns the wrapped first element of the singular-via-list edge,
// or nil if the list is empty.
func (e *Studio) HomeBase() *Country {
	if len(e.Unwrap().HomeBase) == 0 || e.Unwrap().HomeBase[0] == nil {
		return nil
	}
	return &Country{Wrapper: typed.WrapValue(e.Unwrap().HomeBase[0])}
}

// SetHomeBase replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetHomeBase(v *Country) {
	if v == nil {
		e.Unwrap().HomeBase = nil
		return
	}
	e.Unwrap().HomeBase = []*schema.Country{v.Unwrap()}
}

// ParentCompany returns the wrapped first element of the singular-via-list edge,
// or nil if the list is empty.
func (e *Studio) ParentCompany() *Country {
	if len(e.Unwrap().ParentCompany) == 0 || e.Unwrap().ParentCompany[0] == nil {
		return nil
	}
	return &Country{Wrapper: typed.WrapValue(e.Unwrap().ParentCompany[0])}
}

// SetParentCompany replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetParentCompany(v *Country) {
	if v == nil {
		e.Unwrap().ParentCompany = nil
		return
	}
	e.Unwrap().ParentCompany = []*schema.Country{v.Unwrap()}
}

// Films returns a freshly allocated slice of wrappers over each
// Film in the multi-edge.
func (e *Studio) Films() []*Film {
	out := make([]*Film, len(e.Unwrap().Films))
	for i, x := range e.Unwrap().Films {
		out[i] = &Film{Wrapper: typed.WrapValue(x)}
	}
	return out
}

// FilmsSeq returns an iterator over the wrapped Films, avoiding
// the allocation in Films().
func (e *Studio) FilmsSeq() iter.Seq[*Film] {
	return func(yield func(*Film) bool) {
		for _, x := range e.Unwrap().Films {
			if !yield(&Film{Wrapper: typed.WrapValue(x)}) {
				return
			}
		}
	}
}

// SetFilms replaces the multi-edge with the given items.
func (e *Studio) SetFilms(items ...*Film) {
	e.Unwrap().Films = make([]*schema.Film, len(items))
	for i, x := range items {
		e.Unwrap().Films[i] = x.Unwrap()
	}
}

// AppendFilms appends items to the multi-edge.
func (e *Studio) AppendFilms(items ...*Film) {
	for _, x := range items {
		e.Unwrap().Films = append(e.Unwrap().Films, x.Unwrap())
	}
}

// RemoveFilms removes elements with any of the given UIDs from the multi-edge.
func (e *Studio) RemoveFilms(uids ...string) {
	e.Unwrap().Films = slices.DeleteFunc(e.Unwrap().Films, func(x *schema.Film) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// Advisors returns a freshly allocated slice of wrappers over each
// Director in the multi-edge.
func (e *Studio) Advisors() []*Director {
	out := make([]*Director, len(e.Unwrap().Advisors))
	for i, x := range e.Unwrap().Advisors {
		out[i] = &Director{Wrapper: typed.WrapValue(x)}
	}
	return out
}

// AdvisorsSeq returns an iterator over the wrapped Directors, avoiding
// the allocation in Advisors().
func (e *Studio) AdvisorsSeq() iter.Seq[*Director] {
	return func(yield func(*Director) bool) {
		for _, x := range e.Unwrap().Advisors {
			if !yield(&Director{Wrapper: typed.WrapValue(x)}) {
				return
			}
		}
	}
}

// SetAdvisors replaces the multi-edge with the given items.
func (e *Studio) SetAdvisors(items ...*Director) {
	e.Unwrap().Advisors = make([]*schema.Director, len(items))
	for i, x := range items {
		e.Unwrap().Advisors[i] = x.Unwrap()
	}
}

// AppendAdvisors appends items to the multi-edge.
func (e *Studio) AppendAdvisors(items ...*Director) {
	for _, x := range items {
		e.Unwrap().Advisors = append(e.Unwrap().Advisors, x.Unwrap())
	}
}

// RemoveAdvisors removes elements with any of the given UIDs from the multi-edge.
func (e *Studio) RemoveAdvisors(uids ...string) {
	e.Unwrap().Advisors = slices.DeleteFunc(e.Unwrap().Advisors, func(x *schema.Director) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// Tags returns the scalar slice.
func (e *Studio) Tags() []string { return e.Unwrap().Tags }

// SetTags sets the scalar slice.
func (e *Studio) SetTags(v []string) { e.Unwrap().Tags = v }

// AppendTags appends values to the scalar slice.
func (e *Studio) AppendTags(v ...string) {
	e.Unwrap().Tags = append(e.Unwrap().Tags, v...)
}

// RemoveTagsFunc removes all elements for which fn returns true.
func (e *Studio) RemoveTagsFunc(fn func(string) bool) {
	e.Unwrap().Tags = slices.DeleteFunc(e.Unwrap().Tags, fn)
}

// Scores returns the scalar slice.
func (e *Studio) Scores() []int { return e.Unwrap().Scores }

// SetScores sets the scalar slice.
func (e *Studio) SetScores(v []int) { e.Unwrap().Scores = v }

// AppendScores appends values to the scalar slice.
func (e *Studio) AppendScores(v ...int) {
	e.Unwrap().Scores = append(e.Unwrap().Scores, v...)
}

// RemoveScoresFunc removes all elements for which fn returns true.
func (e *Studio) RemoveScoresFunc(fn func(int) bool) {
	e.Unwrap().Scores = slices.DeleteFunc(e.Unwrap().Scores, fn)
}

// Weights returns the scalar slice.
func (e *Studio) Weights() []float64 { return e.Unwrap().Weights }

// SetWeights sets the scalar slice.
func (e *Studio) SetWeights(v []float64) { e.Unwrap().Weights = v }

// AppendWeights appends values to the scalar slice.
func (e *Studio) AppendWeights(v ...float64) {
	e.Unwrap().Weights = append(e.Unwrap().Weights, v...)
}

// RemoveWeightsFunc removes all elements for which fn returns true.
func (e *Studio) RemoveWeightsFunc(fn func(float64) bool) {
	e.Unwrap().Weights = slices.DeleteFunc(e.Unwrap().Weights, fn)
}

// Flags returns the scalar slice.
func (e *Studio) Flags() []bool { return e.Unwrap().Flags }

// SetFlags sets the scalar slice.
func (e *Studio) SetFlags(v []bool) { e.Unwrap().Flags = v }

// AppendFlags appends values to the scalar slice.
func (e *Studio) AppendFlags(v ...bool) {
	e.Unwrap().Flags = append(e.Unwrap().Flags, v...)
}

// RemoveFlagsFunc removes all elements for which fn returns true.
func (e *Studio) RemoveFlagsFunc(fn func(bool) bool) {
	e.Unwrap().Flags = slices.DeleteFunc(e.Unwrap().Flags, fn)
}

// Milestones returns the scalar slice.
func (e *Studio) Milestones() []time.Time { return e.Unwrap().Milestones }

// SetMilestones sets the scalar slice.
func (e *Studio) SetMilestones(v []time.Time) { e.Unwrap().Milestones = v }

// AppendMilestones appends values to the scalar slice.
func (e *Studio) AppendMilestones(v ...time.Time) {
	e.Unwrap().Milestones = append(e.Unwrap().Milestones, v...)
}

// RemoveMilestonesFunc removes all elements for which fn returns true.
func (e *Studio) RemoveMilestonesFunc(fn func(time.Time) bool) {
	e.Unwrap().Milestones = slices.DeleteFunc(e.Unwrap().Milestones, fn)
}
