// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"context"

	"github.com/matthewmcneely/modusgraph"
	"github.com/matthewmcneely/modusgraph/typed"

	"github.com/matthewmcneely/modusgraph/cmd/modusgraph-gen/internal/parser/testdata/movies/schema"
)

// StudioClient provides CRUD/query operations over Studio wrapper values.
// It composes over a typed.Client bound to the schema struct: reads wrap the
// schema result, writes forward the wrapper's backing struct.
type StudioClient struct {
	typed *typed.Client[schema.Studio]
}

// NewStudioClient binds a StudioClient to conn.
func NewStudioClient(conn modusgraph.Client) *StudioClient {
	return &StudioClient{typed: typed.NewClient[schema.Studio](conn)}
}

// Get loads the Studio with the given UID and returns it wrapped.
func (c *StudioClient) Get(ctx context.Context, uid string) (*Studio, error) {
	s, err := c.typed.Get(ctx, uid)
	if err != nil {
		return nil, err
	}
	return WrapStudio(s), nil
}

// Add inserts the schema struct backing w.
func (c *StudioClient) Add(ctx context.Context, w *Studio) error {
	return c.typed.Add(ctx, w.Unwrap())
}

// Update modifies the schema struct backing w (must have UID set).
func (c *StudioClient) Update(ctx context.Context, w *Studio) error {
	return c.typed.Update(ctx, w.Unwrap())
}

// Upsert inserts or updates the schema struct backing w, matching against
// predicates. With no predicates, the first dgraph:"upsert" field wins.
func (c *StudioClient) Upsert(ctx context.Context, w *Studio, predicates ...string) error {
	return c.typed.Upsert(ctx, w.Unwrap(), predicates...)
}

// Delete removes the Studio with the given UID.
func (c *StudioClient) Delete(ctx context.Context, uid string) error {
	return c.typed.Delete(ctx, uid)
}

// Query returns a wrapper-side query builder for Studio.
func (c *StudioClient) Query(ctx context.Context) *StudioQuery {
	return &StudioQuery{typed: c.typed.Query(ctx)}
}
