// Code generated by modusGraphGen. DO NOT EDIT.

package movies

import (
	"iter"
	"slices"

	"github.com/mlwelles/modusGraphMoviesProject/schema"
)

// Name returns the name field.
func (e *Studio) Name() string { return e.s.Name }

// SetName sets the name field.
func (e *Studio) SetName(v string) { e.s.Name = v }

// YearFounded returns the yearFounded field.
func (e *Studio) YearFounded() int { return e.s.YearFounded }

// SetYearFounded sets the yearFounded field.
func (e *Studio) SetYearFounded(v int) { e.s.YearFounded = v }

// Revenue returns the revenue field.
func (e *Studio) Revenue() float64 { return e.s.Revenue }

// SetRevenue sets the revenue field.
func (e *Studio) SetRevenue(v float64) { e.s.Revenue = v }

// Active returns the active field.
func (e *Studio) Active() bool { return e.s.Active }

// SetActive sets the active field.
func (e *Studio) SetActive(v bool) { e.s.Active = v }

// CreatedAt returns the createdAt field.
func (e *Studio) CreatedAt() time.Time { return e.s.CreatedAt }

// SetCreatedAt sets the createdAt field.
func (e *Studio) SetCreatedAt(v time.Time) { e.s.CreatedAt = v }

// Embedding returns the embedding field.
func (e *Studio) Embedding() *dg.VectorFloat32 { return e.s.Embedding }

// SetEmbedding sets the embedding field.
func (e *Studio) SetEmbedding(v *dg.VectorFloat32) { e.s.Embedding = v }

// Founder returns the wrapped Director, or nil if not set.
// Shared state: mutations through the returned wrapper write through to e.s.
func (e *Studio) Founder() *Director {
	if e.s.Founder == nil {
		return nil
	}
	return &Director{s: e.s.Founder}
}

// SetFounder sets or clears the Director edge.
func (e *Studio) SetFounder(v *Director) {
	if v == nil {
		e.s.Founder = nil
		return
	}
	e.s.Founder = v.s
}

// Headquarters returns a wrapper over the value-typed schema field. The wrapper
// shares state with e — mutations are visible to e immediately.
func (e *Studio) Headquarters() *Country {
	return &Country{s: &e.s.Headquarters}
}

// SetHeadquarters copies the value from v into the schema field. Note: this is
// a value copy, so v and e.Headquarters() will not share state after this call.
func (e *Studio) SetHeadquarters(v *Country) {
	if v != nil {
		e.s.Headquarters = *v.s
	}
}

// CurrentHead returns the wrapped first element of the singular-via-list edge,
// or nil if the list is empty.
func (e *Studio) CurrentHead() *Director {
	if len(e.s.CurrentHead) == 0 || e.s.CurrentHead[0] == nil {
		return nil
	}
	return &Director{s: e.s.CurrentHead[0]}
}

// SetCurrentHead replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetCurrentHead(v *Director) {
	if v == nil {
		e.s.CurrentHead = nil
		return
	}
	e.s.CurrentHead = []*schema.Director{v.s}
}

// Ceo returns the wrapped first element of the singular-via-list edge,
// or nil if the list is empty.
func (e *Studio) Ceo() *Director {
	if len(e.s.Ceo) == 0 || e.s.Ceo[0] == nil {
		return nil
	}
	return &Director{s: e.s.Ceo[0]}
}

// SetCeo replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetCeo(v *Director) {
	if v == nil {
		e.s.Ceo = nil
		return
	}
	e.s.Ceo = []*schema.Director{v.s}
}

// HomeBase returns the wrapped first element of the singular-via-list edge,
// or nil if the list is empty.
func (e *Studio) HomeBase() *Country {
	if len(e.s.HomeBase) == 0 || e.s.HomeBase[0] == nil {
		return nil
	}
	return &Country{s: e.s.HomeBase[0]}
}

// SetHomeBase replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetHomeBase(v *Country) {
	if v == nil {
		e.s.HomeBase = nil
		return
	}
	e.s.HomeBase = []*schema.Country{v.s}
}

// ParentCompany returns the wrapped first element of the singular-via-list edge,
// or nil if the list is empty.
func (e *Studio) ParentCompany() *Country {
	if len(e.s.ParentCompany) == 0 || e.s.ParentCompany[0] == nil {
		return nil
	}
	return &Country{s: e.s.ParentCompany[0]}
}

// SetParentCompany replaces the singular-via-list edge with v, or clears it if nil.
func (e *Studio) SetParentCompany(v *Country) {
	if v == nil {
		e.s.ParentCompany = nil
		return
	}
	e.s.ParentCompany = []*schema.Country{v.s}
}

// Films returns a freshly allocated slice of wrappers over each
// Film in the multi-edge.
func (e *Studio) Films() []*Film {
	out := make([]*Film, len(e.s.Films))
	for i, x := range e.s.Films {
		out[i] = &Film{s: x}
	}
	return out
}

// FilmsSeq returns an iterator over the wrapped Films, avoiding
// the allocation in Films().
func (e *Studio) FilmsSeq() iter.Seq[*Film] {
	return func(yield func(*Film) bool) {
		for _, x := range e.s.Films {
			if !yield(&Film{s: x}) {
				return
			}
		}
	}
}

// SetFilms replaces the multi-edge with the given items.
func (e *Studio) SetFilms(items ...*Film) {
	e.s.Films = make([]*schema.Film, len(items))
	for i, x := range items {
		e.s.Films[i] = x.s
	}
}

// AppendFilms appends items to the multi-edge.
func (e *Studio) AppendFilms(items ...*Film) {
	for _, x := range items {
		e.s.Films = append(e.s.Films, x.s)
	}
}

// RemoveFilms removes elements with any of the given UIDs from the multi-edge.
func (e *Studio) RemoveFilms(uids ...string) {
	e.s.Films = slices.DeleteFunc(e.s.Films, func(x *schema.Film) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// Advisors returns a freshly allocated slice of wrappers over each
// Director in the multi-edge.
func (e *Studio) Advisors() []*Director {
	out := make([]*Director, len(e.s.Advisors))
	for i, x := range e.s.Advisors {
		out[i] = &Director{s: x}
	}
	return out
}

// AdvisorsSeq returns an iterator over the wrapped Directors, avoiding
// the allocation in Advisors().
func (e *Studio) AdvisorsSeq() iter.Seq[*Director] {
	return func(yield func(*Director) bool) {
		for _, x := range e.s.Advisors {
			if !yield(&Director{s: x}) {
				return
			}
		}
	}
}

// SetAdvisors replaces the multi-edge with the given items.
func (e *Studio) SetAdvisors(items ...*Director) {
	e.s.Advisors = make([]*schema.Director, len(items))
	for i, x := range items {
		e.s.Advisors[i] = x.s
	}
}

// AppendAdvisors appends items to the multi-edge.
func (e *Studio) AppendAdvisors(items ...*Director) {
	for _, x := range items {
		e.s.Advisors = append(e.s.Advisors, x.s)
	}
}

// RemoveAdvisors removes elements with any of the given UIDs from the multi-edge.
func (e *Studio) RemoveAdvisors(uids ...string) {
	e.s.Advisors = slices.DeleteFunc(e.s.Advisors, func(x *schema.Director) bool {
		return x != nil && slices.Contains(uids, x.UID)
	})
}

// Tags returns the scalar slice.
func (e *Studio) Tags() []string { return e.s.Tags }

// SetTags sets the scalar slice.
func (e *Studio) SetTags(v []string) { e.s.Tags = v }

// AppendTags appends values to the scalar slice.
func (e *Studio) AppendTags(v ...string) {
	e.s.Tags = append(e.s.Tags, v...)
}

// RemoveTagsFunc removes all elements for which fn returns true.
func (e *Studio) RemoveTagsFunc(fn func(string) bool) {
	e.s.Tags = slices.DeleteFunc(e.s.Tags, fn)
}

// Scores returns the scalar slice.
func (e *Studio) Scores() []int { return e.s.Scores }

// SetScores sets the scalar slice.
func (e *Studio) SetScores(v []int) { e.s.Scores = v }

// AppendScores appends values to the scalar slice.
func (e *Studio) AppendScores(v ...int) {
	e.s.Scores = append(e.s.Scores, v...)
}

// RemoveScoresFunc removes all elements for which fn returns true.
func (e *Studio) RemoveScoresFunc(fn func(int) bool) {
	e.s.Scores = slices.DeleteFunc(e.s.Scores, fn)
}

// Weights returns the scalar slice.
func (e *Studio) Weights() []float64 { return e.s.Weights }

// SetWeights sets the scalar slice.
func (e *Studio) SetWeights(v []float64) { e.s.Weights = v }

// AppendWeights appends values to the scalar slice.
func (e *Studio) AppendWeights(v ...float64) {
	e.s.Weights = append(e.s.Weights, v...)
}

// RemoveWeightsFunc removes all elements for which fn returns true.
func (e *Studio) RemoveWeightsFunc(fn func(float64) bool) {
	e.s.Weights = slices.DeleteFunc(e.s.Weights, fn)
}

// Flags returns the scalar slice.
func (e *Studio) Flags() []bool { return e.s.Flags }

// SetFlags sets the scalar slice.
func (e *Studio) SetFlags(v []bool) { e.s.Flags = v }

// AppendFlags appends values to the scalar slice.
func (e *Studio) AppendFlags(v ...bool) {
	e.s.Flags = append(e.s.Flags, v...)
}

// RemoveFlagsFunc removes all elements for which fn returns true.
func (e *Studio) RemoveFlagsFunc(fn func(bool) bool) {
	e.s.Flags = slices.DeleteFunc(e.s.Flags, fn)
}

// Milestones returns the scalar slice.
func (e *Studio) Milestones() []time.Time { return e.s.Milestones }

// SetMilestones sets the scalar slice.
func (e *Studio) SetMilestones(v []time.Time) { e.s.Milestones = v }

// AppendMilestones appends values to the scalar slice.
func (e *Studio) AppendMilestones(v ...time.Time) {
	e.s.Milestones = append(e.s.Milestones, v...)
}

// RemoveMilestonesFunc removes all elements for which fn returns true.
func (e *Studio) RemoveMilestonesFunc(fn func(time.Time) bool) {
	e.s.Milestones = slices.DeleteFunc(e.s.Milestones, fn)
}
